### ISSUE TITLE
Support JavaScript style comments

### ISSUE THREAD

**Issue by akheron** [akheron/jansson#13]
See https://groups.google.com/d/topic/jansson-users/b5-KA0TM3eA/discussion for the suggestion by Basile Starynkevich

**Comment by neopaf** [comment]
akheron, please give any grounds?
We want it as an option, default off.
If not passed, standard approach, and nobody hurt.

But we definitely need it.

Our grounds: 
we plan to use configs as JSON, and in configs 100% sysadmins in the world want comments.
