### ISSUE TITLE
crash on jsonp_free(key)

### ISSUE THREAD

**Issue by ecks** [akheron/jansson#148]
When I parse a json formatted string using json_loads, the program crashes at parse_object function. From the trace I get, key is initialized with call 

 key = lex_steal_string(lex);

and then crashes a couple lines later at jsonp_free(key). Oddly enough, the crash does not occur when I am running the program with valgrind. The backtrace I get is

**\* glibc detected **\* ./test: invalid fastbin entry (free): 0x000000000205b260 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7eb96)[0x7fac5b846b96]
/usr/local/lib/libjansson.so.4(+0x44fd)[0x7fac5c2bf4fd]
/usr/local/lib/libjansson.so.4(+0x4819)[0x7fac5c2bf819]
/usr/local/lib/libjansson.so.4(json_loads+0x7a)[0x7fac5c2bf94a]
./test[0x418564]
./test[0x404994]
./test[0x437b0e]
./test[0x435eb5]
./test[0x43765a]
./test[0x437b0e]
./test[0x435e5c]
./test[0x439451]
./test[0x42f188]
./test[0x42f2e1]
./test[0x42f3f8]
./test[0x4043c9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7fac5b7e976d]
./test[0x4042e9]
======= Memory map: ========
00400000-00453000 r-xp 00000000 fc:00 132030                             /home/hasenov/zebralite/ospf6-sibling/test
00652000-00657000 r--p 00052000 fc:00 132030                             /home/hasenov/zebralite/ospf6-sibling/test
00657000-00659000 rw-p 00057000 fc:00 132030                             /home/hasenov/zebralite/ospf6-sibling/test
00659000-0065f000 rw-p 00000000 00:00 0 
02058000-02079000 rw-p 00000000 00:00 0                                  [heap]
7fac5b4cc000-7fac5b5c7000 r-xp 00000000 fc:00 47554                      /lib/x86_64-linux-gnu/libm-2.15.so
7fac5b5c7000-7fac5b7c6000 ---p 000fb000 fc:00 47554                      /lib/x86_64-linux-gnu/libm-2.15.so
7fac5b7c6000-7fac5b7c7000 r--p 000fa000 fc:00 47554                      /lib/x86_64-linux-gnu/libm-2.15.so
7fac5b7c7000-7fac5b7c8000 rw-p 000fb000 fc:00 47554                      /lib/x86_64-linux-gnu/libm-2.15.so
7fac5b7c8000-7fac5b97d000 r-xp 00000000 fc:00 47532                      /lib/x86_64-linux-gnu/libc-2.15.so
7fac5b97d000-7fac5bb7d000 ---p 001b5000 fc:00 47532                      /lib/x86_64-linux-gnu/libc-2.15.so
7fac5bb7d000-7fac5bb81000 r--p 001b5000 fc:00 47532                      /lib/x86_64-linux-gnu/libc-2.15.so
7fac5bb81000-7fac5bb83000 rw-p 001b9000 fc:00 47532                      /lib/x86_64-linux-gnu/libc-2.15.so
7fac5bb83000-7fac5bb88000 rw-p 00000000 00:00 0 
7fac5bb88000-7fac5bba0000 r-xp 00000000 fc:00 47550                      /lib/x86_64-linux-gnu/libpthread-2.15.so
7fac5bba0000-7fac5bd9f000 ---p 00018000 fc:00 47550                      /lib/x86_64-linux-gnu/libpthread-2.15.so
7fac5bd9f000-7fac5bda0000 r--p 00017000 fc:00 47550                      /lib/x86_64-linux-gnu/libpthread-2.15.so
7fac5bda0000-7fac5bda1000 rw-p 00018000 fc:00 47550                      /lib/x86_64-linux-gnu/libpthread-2.15.so
7fac5bda1000-7fac5bda5000 rw-p 00000000 00:00 0 
7fac5bda5000-7fac5bdba000 r-xp 00000000 fc:00 1079                       /lib/x86_64-linux-gnu/libgcc_s.so.1
7fac5bdba000-7fac5bfb9000 ---p 00015000 fc:00 1079                       /lib/x86_64-linux-gnu/libgcc_s.so.1
7fac5bfb9000-7fac5bfba000 r--p 00014000 fc:00 1079                       /lib/x86_64-linux-gnu/libgcc_s.so.1
7fac5bfba000-7fac5bfbb000 rw-p 00015000 fc:00 1079                       /lib/x86_64-linux-gnu/libgcc_s.so.1
7fac5bfbb000-7fac5c09d000 r-xp 00000000 fc:00 6765                       /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.16
7fac5c09d000-7fac5c29c000 ---p 000e2000 fc:00 6765                       /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.16
7fac5c29c000-7fac5c2a4000 r--p 000e1000 fc:00 6765                       /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.16
7fac5c2a4000-7fac5c2a6000 rw-p 000e9000 fc:00 6765                       /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.16
7fac5c2a6000-7fac5c2bb000 rw-p 00000000 00:00 0 
7fac5c2bb000-7fac5c2c6000 r-xp 00000000 fc:00 2106                       /usr/local/lib/libjansson.so.4.5.0
7fac5c2c6000-7fac5c4c5000 ---p 0000b000 fc:00 2106                       /usr/local/lib/libjansson.so.4.5.0
7fac5c4c5000-7fac5c4c6000 r--p 0000a000 fc:00 2106                       /usr/local/lib/libjansson.so.4.5.0
7fac5c4c6000-7fac5c4c7000 rw-p 0000b000 fc:00 2106                       /usr/local/lib/libjansson.so.4.5.0
7fac5c4c7000-7fac5c4ce000 r-xp 00000000 fc:00 47546                      /lib/x86_64-linux-gnu/librt-2.15.so
7fac5c4ce000-7fac5c6cd000 ---p 00007000 fc:00 47546                      /lib/x86_64-linux-gnu/librt-2.15.so
7fac5c6cd000-7fac5c6ce000 r--p 00006000 fc:00 47546                      /lib/x86_64-linux-gnu/librt-2.15.so
7fac5c6ce000-7fac5c6cf000 rw-p 00007000 fc:00 47546                      /lib/x86_64-linux-gnu/librt-2.15.so
7fac5c6cf000-7fac5c6f1000 r-xp 00000000 fc:00 47556                      /lib/x86_64-linux-gnu/ld-2.15.so
7fac5c8e2000-7fac5c8e8000 rw-p 00000000 00:00 0 
7fac5c8ed000-7fac5c8f1000 rw-p 00000000 00:00 0 
7fac5c8f1000-7fac5c8f2000 r--p 00022000 fc:00 47556                      /lib/x86_64-linux-gnu/ld-2.15.so
7fac5c8f2000-7fac5c8f4000 rw-p 00023000 fc:00 47556                      /lib/x86_64-linux-gnu/ld-2.15.so
7fff7093f000-7fff70960000 rw-p 00000000 00:00 0                          [stack]
7fff709ff000-7fff70a00000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
zsh: abort (core dumped)  ./test

**Comment by balag1986** [comment]
hi ecks

Could you share what the actual problem was, i am facing the same problem and i might be doing the same mistake. please let know, thanks
