### ISSUE TITLE
Non-standard JSON features support

### ISSUE THREAD

**Issue by Sannis** [akheron/jansson#215]
Some JSON parsers/writers support non-standard JSON features like comments and trailing commas. @akheron, whats your opinion about that? Are you welcome for patches that will add such optional functionality to Jansson?

**Comment by akheron** [comment]
No. Those have been proposed multiple times in the past, and have been rejected.

**Comment by neopaf** [comment]
I understand if this was to change base parsing mode.
But optional?
For those who really need it?

Our grounds: 
we plan to use configs as JSON, and in configs 100% sysadmins in the world want comments.
