### ISSUE TITLE
recursive json_object_foreach

### ISSUE THREAD

**Issue by anupamme** [akheron/jansson#220]
json_object_foreach(root, key, value) {
   printf("key: %s", key);
   print_json(value);
   json_object_foreach(value, cuisine, items) {
      printf("cuisine: %s", cuisine);
      print_json(items);
   }
}

This does not compile. I think it is because I am using foreach in recursive. Is that correct or I am doing something wrong?

**Comment by akheron** [comment]
Have you declared the variables used for iteration? This compiles just fine for me (I commented out the `print_json` calls as it's not declared for me):

```c
#include <stdio.h>
#include <string.h>
#include <jansson.h>

int main() {
    json_t *root, *value, *items;
    const char *key, *cuisine;

    json_object_foreach(root, key, value) {
        printf("key: %s", key);
        /* print_json(value); */
        json_object_foreach(value, cuisine, items) {
            printf("cuisine: %s", cuisine);
            /* print_json(items); */
        }
    }
    return 0;
}
```

**Comment by anupamme** [comment]
There was problem at my end. Thanks for clarification.
