### ISSUE TITLE
unexplained valgrind errors

### ISSUE THREAD

**Issue by chrisdew** [akheron/jansson#222]
I'm sorry that I can't immediately spend a day isolating a test case for this, but I wanted to post it anyway.

I have some json_string's which are reference by mutiple roots.  When I tried the approach of using json_incref() for each new reference, I got memory leaks.  When I make new json_strings, it works.

What should I be doing?

```
    			if (json_integer_value(number) == (json_int_t) varint) {
    				// this makes valgrind report memory leaks
    				/*
    				json_incref(name);
    				return_value = name;
    				*/

    				// this makes valgrind report invalid reads and writes
    				/*
    				return_value = name;
    				*/

    				// this makes valgrind happy
    				return_value = json_string(json_string_value(name));

    				break;
    			}
```

`name` is a `json_string_t`, `number` is a `json_integer_t`.

There's no urgency to this, as the third option is a workable solution and only takes a few KB extra at runtime.

I'm more concerned that I don't understand Jansson's implementation of reference counting.

**Comment by akheron** [comment]
Using `json_incref(name)` is fine and should work as you expected. There must be something else wrong in your program that's causing the memory leaks.
