### ISSUE TITLE
Not writing to file

### ISSUE THREAD

**Issue by WillLuce** [akheron/jansson#223]
Hey guys. I'm having a problem with a function not writing to file. Here's the function and the JSON is gives on json_dumps(), but json_dump_file() is throwing -1. Also, even in the json_dumps(), there are instances of not writing the gradient variable. Any suggestions?

    void Route::writeRouteToJSON(string file_name)
    {
        string file_path = "/Users/williamluce/Projects/MeteoVelo/Data/" + file_name + ".json";
        cout << "Writing to file at: " + file_path << endl;
        const char* outFile = (char*)file_path.c_str();
    
        json_t *root, *points;
        root = json_object();                                                   // initialize the root object
        points = json_array();                                                  // points array holds the data from the route nodes
    
        json_object_set_new(root, "points", points);                            // append the points array to the root
    
        /* Append Route global variables */
        char* name = (char*)RouteName.c_str();                                  // json_string constructor takes in a char*
        json_object_set_new(root, "routeName", json_string(name));
        json_object_set_new(root, "totalDistance", json_real(TotalDistance));
    
         /*
         Populate the points data by interating through the nodeData vector and
         creating a new json value out of each member of the struct route_node.
         */
        for (vector<route_node>::iterator it = route.begin(); it != route.end(); ++it)
        {
            json_t *point = json_object();
        
            json_object_set_new(point, "latitude", json_real(it->latitude));
            json_object_set_new(point, "longitude", json_real(it->longitude));
            json_object_set_new(point, "elevation", json_real(it->elevation));
            json_object_set_new(point, "distance", json_real(it->distance));
            json_object_set_new(point, "gradient", json_real(it->gradient));
            json_object_set_new(point, "heading", json_real(it->heading));
        
            json_array_append_new(points, point);
        }
    
        int buildFile = json_dump_file(points, outFile, JSON_INDENT(3));
        char *dump = json_dumps(root, JSON_INDENT(3));
        cout << dump << endl;
    
        if (buildFile == 0)
        {
            cout << "Success, the Route JSON file has been created!" << endl;
        }
        else
        {
           cout << "There was a problem building the Route JSON file!" << endl;
        } 
    }

{
   "points": [
      {
         "heading": 329.62286376953125,
         "elevation": 0.87,
         "latitude": 43.8964,
         "longitude": 10.22444,
         "distance": 0.0,
         "gradient": 0.023474179208278656
      },
      {
         "heading": 304.41595458984375,
         "elevation": 1.02,
         "latitude": 43.901350000000001,
         "longitude": 10.220409999999999,
         "distance": 639.0,
         "gradient": 0.038461539894342422
      },
      {
         "heading": 304.93557739257812,
         "elevation": 1.03,
         "latitude": 43.901479999999999,
         "longitude": 10.220140000000001,
         "distance": 665.0,
         "gradient": -0.037037037312984467
      },
      {
         "heading": 307.70059204101562,
         "elevation": 1.01,
         "latitude": 43.901760000000003,
         "longitude": 10.21959,
         "distance": 719.0,
         "gradient": -0.37037035822868347
      },
      {
         "heading": 315.373046875,
         "elevation": 0.91000000000000003,
         "latitude": 43.901910000000001,
         "longitude": 10.21932,
         "distance": 746.0,
         "gradient": -0.36000001430511475
      },
      {
         "heading": 332.778564453125,
         "elevation": 0.81999999999999995,
         "latitude": 43.902070000000002,
         "longitude": 10.219099999999999,
         "distance": 771.0,
         "gradient": -0.0555555559694767
      },
      {
         "heading": 0.0,
         "elevation": 0.81000000000000005,
         "latitude": 43.902209999999997,
         "longitude": 10.218999999999999,
         "distance": 789.0
      },
      {
         "heading": 331.8133544921875,
         "elevation": 0.81000000000000005,
         "latitude": 43.902209999999997,
         "longitude": 10.218999999999999,
         "distance": 789.0,
         "gradient": 0.12380952388048172
      }   
   ],
   "routeName": "2015 Tirreno Adriatico TTT",
   "totalDistance": 22696.0
}

**Comment by akheron** [comment]
Could you run the test suite? It contains a test that checks whether `json_dump_file()` works as expected in your system. Assuming you're on OS X, just run `make check` after running the configure script.

It's also possible that the file you're trying to write is not writable, or has some other problem. You can try to use `perror()` or `strerror()` immediately after calling `json_dump_file()` to find out whether `fopen()` fails and which error message it produces.

**Comment by WillLuce** [comment]
I have my code pasted on the question. Looks like it's saying there's no
such file in the directory. Do I need to fopen() and fclose()? I though
jansson did that for me.

**Comment by akheron** [comment]
Jansson calls `fopen(filename, "w")` and later `fclose()` under the hood. But if the `fopen()` call fails, the `errno` variable set by it is retained and that's why you get the error message with `perror()` and `strerror()`.

If the error message is "No such file or directory", ENOENT, or something like that, most probably some of the parent directories doesn't exist.

**Comment by WillLuce** [comment]
Got it. Thank you. I'm not at my computer right now, but I'm almost
positive that's it.
