### ISSUE TITLE
Support `"\u0000"` in object keys.

### ISSUE THREAD

**Issue by starrify** [akheron/jansson#228]
Currently `jansson` supports character `"\u0000"` in strings by setting the value via `json_stringn`. That's good.

However with object keys the only type that the current API supports is `const char *`, e.g. in `json_object_get` and `json_object_set`. That makes it impossible to build a value like:
```json
{
    "test\u0000message": True
}
```

Could we add a set of API that supports `json_t` as the type of object keys?

**Comment by akheron** [comment]
Supporting `json_t` object keys wouldn't make much sense, as JSON object keys can only be strings. Furthermore, coercing other value types to strings automatically would be too surprising for most users and therefore would cause bugs.

Adding another set of `json_object_*` functions that can deal with non-null-terminated keys would be API bloat for such a rarely requested feature. We would need new versions of:
- `json_object_get()`
- `json_object_set()`
- `json_object_set_new()`
- `json_object_set_nocheck()`
- `json_object_set_new_nocheck()`
- `json_object_iter_at()`
