### ISSUE TITLE
hjson support

### ISSUE THREAD

**Issue by dtoubelis** [akheron/jansson#232]
I think requests for support of comments in json is the topic beaten to death. However, there is an effort to somehow alleviate this problem at http://hjson.org/. Would you consider implementing it it in jansson library? It could be an extra parameter to the parser/loader to allow relaxed syntax or a property of json_t object. Without it this parameter/property everything would  behaves as usual but if specified it would allow for the relaxed syntax.

Comments in json is a pain point for everybody and hjson effort seems like reasonable compromise, so I think supporting it would be a good thing for the community in general.

**Comment by akheron** [comment]
I've categorically rejected all such requests. There are many variations of JSON, and everyone seems to prefer one of them, so it's best to stick to pure JSON. Any syntax extensions should be implemented as separate libraries.
