### ISSUE TITLE
feature enhancement: strip javascript comments in lexer

### ISSUE THREAD

**Issue by jerryjacobs** [akheron/jansson#235]
I implemented a working draft to strip singleline and multiline comments from JSON.
Multiline: /* comment \n next line comment*/
Singleline: //comment\n

I did functional testing and have not implemented json flag and test cases yet:
https://github.com/jerryjacobs/jansson/tree/comment

This feature is usefull when using jansson for reading application configuration and adding javascript style comments inside the configuration file.

Kind regards,
Jerry

**Comment by akheron** [comment]
I've categorically rejected all requests of adding support for non-standard JSON syntax, like comments.

**Comment by neopaf** [comment]
akheron, please give any grounds?
We want it as an option, default off.
But we definitely need it.

Our grounds: 
we plan to use configs as JSON, and in configs 100% sysadmins in the world want comments.

**Comment by jerryjacobs** [comment]
Before you feed JSON to a json library you could strip the single/multiline comments with my C application I created for this purpose here: 
https://github.com/jerryjacobs/striptease

**Comment by neopaf** [comment]
@jerryjacobs, I still hope to persuade Petri (@akheron).

And yes, we'd have to do something like that if he'll refuse (it's his project = his rules).
Thanks for sharing.

**Comment by jerryjacobs** [comment]
it should be possible for the library by adding a extra flag to use the strip comments functionality
