### ISSUE TITLE
Get real value from integer

### ISSUE THREAD

**Issue by Cocottier** [akheron/jansson#236]
Hello,

I came here to point out something that might not be an issue, or might be.
I spent some minutes don't understanding why your library did not parsed a json file I generated from a web app, and the cause of the problem was that a real value was in fact an integer value.

To correct it, what I have done was replacing this line:
https://github.com/akheron/jansson/blob/master/src/value.c#L863

by

    return (double)json_integer_value(json);

Take it or leave it, for me it was confusing to consider that integer numbers could not be considered as real numbers.

**Comment by akheron** [comment]
Well yes, in the strict mathematical sense that's a bit confusing. However, there's already `json_number_value()` which accepts both real and integer, and always casts the result to `double`.
