### ISSUE TITLE
json_deep_copy doesnt preserve order

### ISSUE THREAD

**Issue by citaylor** [akheron/jansson#237]
json_deep_copy doesnt preserve order of objects when there are objects with child objects/arrays.
Found in v2.6.

I have example code if required.

**Comment by akheron** [comment]
Yeah, neither does json_copy. I think the best resolution is to document this behavior for now. If suppot for iterating object keys in insertion order is added later, this can be fixed by adding a separate copy and deep copy functions that preserve insertion order.
