### ISSUE TITLE
JSON tree verification using JSON-schema

### ISSUE THREAD

**Issue by andrevanherk** [akheron/jansson#241]
If you use JSON to exchange data, it's quite convenient to use a JSON-schema to formalize the structure of the data. E.g. the order in which certain attributes can appear, allowed values for a given identifier, etc.

This request is to add a 'tree verification' feature, e.g. by adding a new function `int json_verify(const json_t *root, const json_t *schema)`.

**Comment by akheron** [comment]
Features that are not part of JSON itself should be implemented as separate libraries.
