### ISSUE TITLE
how can i trun json_t to string?

### ISSUE THREAD

**Issue by Eric-918** [akheron/jansson#247]
code like this.

sprintf(topicValue,"{\"topic\":\"%s\",\"partitionNum\":%d}","topic",0); //{"topic":"topic","partitionNum":0}
json_error_t jerror;
json_t *jobj = json_loads(topicValue,0,&jerror);

char *tmp = json_string_value(jobj);
printf("tmp = %s\n", tmp);

but tmp is null, how can i get a string like topicValue from an json_t ?

**Comment by Eric-918** [comment]
code like this.

sprintf(topicValue,"{\"topic\":\"%s\",\"partitionNum\":%d}","topic",0); //{"topic":"topic","partitionNum":0}
json_error_t jerror;
json_t *jobj = json_loads(topicValue,0,&jerror);

char *tmp = json_string_value(jobj);
printf("tmp = %s\n", tmp);

but tmp is null, how can i get a string like topicValue from an json_t ?

**Comment by akheron** [comment]
If you want the "opposite" of json_loads, use json_dumps.
