### ISSUE TITLE
JSON_INTEGER_FORMAT not set in cmake in some cases

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [akheron/jansson#249]
Hello,

I'm doing some cross-compilation and there is a problem when dumping an integer. In fact it seems JSON_INTEGER_FORMAT is not defined in the cmakeList. I read the file and it seems it is defined only in one case : when we don't HAVE_STRTOLL. 

When compiling I get this warning : 

```
/src/dump.c:201:30: warning: 
      incomplete format specifier [-Wformat]
                            "%" JSON_INTEGER_FORMAT,
                             ^
1 warning generated.
```

I replaced `"%" JSON_INTEGER_FORMAT` by `%d` and everything is fine.

So it work on my side but I think you may want a more generic CmakeList.txt.

Best regards,

Guillaume Leclerc

**Comment by akheron** [comment]
It's also defined in the end of `if (NOT DEFINED JSON_INT_T)` branch. By only looking at CMakeLists.txt, it seems to me that it's always defined.
