### ISSUE TITLE
Integer overflow when importing a uint32_t cast as json_int_t

### ISSUE THREAD

**Issue by TLINDEN** [akheron/jansson#250]
I'm trying to import the following number (an example) as JSON: 3632472550 using this code (shortened):
```
  fprintf(stderr, "serial: %lld\n", (json_int_t)sk->serial);
  jout = json_pack(jformat,
[..]
		   "serial", (json_int_t)sk->serial,
```
This is what happens, when I print the serial and dump the resulting JSON:
```
serial: 3632472550
{
    "keys": [
        {
            "serial": -662494746,
[..]
```
Code where I'm doing this: https://github.com/TLINDEN/pcp/blob/master/libpcp/mgmt.c#L924

best,
Tom

**Comment by niyamaka** [comment]
In the format string you must write 'I' instead of 'i' (in all json_int_t types).

**Comment by TLINDEN** [comment]
Thanks a lot, fixed :+1:
