### ISSUE TITLE
Convert Data also to XML Format

### ISSUE THREAD

**Issue by Dinesh-Ramakrishnan** [akheron/jansson#254]
Hi , 

I am using Jansson Library and its api to generate JSON Data.  But I want to build my system to generate either JSON output or XML output based on user request.  But I still want to use the Jansson library and its API for converting to XML output also.  Is it possible currently to use jansson library to convert data to xml format also? if not is it possible to adapt it to do so?  Please provide me some guidelines on this. 

Thank you

**Comment by akheron** [comment]
Jansson is a JSON library and there will be no support for XML. I'm afraid you have to use another library for that purpose.
