### ISSUE TITLE
Add AMBuild support

### ISSUE THREAD

**Issue by WildCard65** [akheron/jansson#259]
Is it too much to ask if this project includes support for compiling with AMBuild( https://github.com/alliedmodders/ambuild ) for making dynamic/static libraries in a style similar to how https://github.com/alliedmodders/sourcepawn/blob/master/AMBuildScript is set up(where if people just want to build jansson via ambuild, it'll configure itself otherwise depend on another project's compile configuration)

**Comment by akheron** [comment]
From https://wiki.alliedmods.net/AMBuild:

> Keep in mind, AMBuild is neither widely used nor has it been used on a wide variety of systems. 

I'm reluctant to add support for build systems that are not widely used.
