### ISSUE TITLE
jsonp_free() would be public

### ISSUE THREAD

**Issue by niyamaka** [akheron/jansson#262]
Hello. 
Why jsonp_free() would be public? 
I'm writing some libraries based in jansson. I cannot use free() safely with the returned value of json_dumps() because someone can have used json_set_alloc_funcs() with other function than free().

Thanks Petri! Great job!

**Comment by akheron** [comment]
Yeah, why not if there's a real use case for it. But I think it would be better to add `json_get_alloc_funcs()` instead.

**Comment by niyamaka** [comment]
Yes, better

**Comment by akheron** [comment]
Fixed, see pull request #264
