### ISSUE TITLE
Buffer on the stack may be a security issue

### ISSUE THREAD

**Issue by npmccallum** [akheron/jansson#266]
An application which intends to store sensitive material in json may set its own allocators to ensure that memory is zeroed before freeing it. Unfortunately, during marshalling and unmarshalling, jansson uses buffers on the stack which do not use the jansson allocators. See, for instance, src/load.c:926. Since they bypass the jansson allocators, an unexpected situation may arise where the sensitive material is placed on the stack (and possibly swapped to disk).

**Comment by akheron** [comment]
This has already been discussed, see: https://groups.google.com/d/msg/jansson-users/xjbW_nXQHBk/Ke2nqbnoMpoJ
