### ISSUE TITLE
Location of a JSON value in the submitted text

### ISSUE THREAD

**Issue by vaplv** [akheron/jansson#272]
Is there any way to retrieve the starting location of a JSON value in the original text (line and column)? This would be particularly useful when the parsed value is JSON compliant but incorrect with respect to the host application. In such case, I would like to be able to notify to the user where the error occurred in its text. For instance, let an interval declared in a JSON file as follow:
        
    {
              ...
      { "lower" : 1.0, "upper" : -1.0 }, 
              ...
    }
    
I would like to print that the interval is invalid and where it is defined. This would help the user to fix this issue.

**Comment by akheron** [comment]
It's not currently possible. I also don't think it's worth adding because it would add unnecessary overhead to each value for a very limited use case.
