### ISSUE TITLE
UTF8 Decoding

### ISSUE THREAD

**Issue by eNTi** [akheron/jansson#276]
hi.

i'm trying to make jansson decode some char *text which holds the following values:
"\303\203\302\244\303\203\302\266\303\203\302\274\303\203\302\204\303\203\302\226\303\203\302\234\303\203\302\237", which are coming from my server and were originally "äöüÄÖÜß".

json_string_value(value); just returns the above byte code. shouldn't json_loads decode this?

**Comment by akheron** [comment]
To what format/encoding do you expect `json_loads()` to decode it? Jansson doesn't transform strings in any way. It just checks that they are valid UTF-8.
