### ISSUE TITLE
Perfomance: json_load* slow?

### ISSUE THREAD

**Issue by serpulga** [akheron/jansson#280]
I've been comparing `jansson` and Python's `json` module, I wanted to see how much `jansson` would kick Python's ass in terms of speed.

I picked up a huge file from: https://github.com/zemirco/sf-city-lots-json (**181 MB**), and setup some code:

```c
// In a nutshell my C code looks this:
clock_t start = clock();
root = json_load_file("sf.json", 0, &error);
clock_t end = clock();
float seconds = (float)(end - start) / CLOCKS_PER_SEC;
printf("Took: %f\n", seconds);
```
**C avg**: ~13 seconds

```python
# My Python code looks like:
start = time.time()
json.load(open('sf.json', 'r'))
end = time.time()
seconds = end - start
print 'Took: ', seconds
```
**Python avg**: ~8

It was a surprise to see how faster the Python code ran compared to the C version.
I know that `jansson` never made any promises about how fast it is, but I'm a bit confused about this.

I'm not very familiar with the internals of any of the two libraries, but I'm wondering if there's a particular reason for this, or if there's a way to make `jansson` run faster.

**Comment by Mephistophiles** [comment]
I checked on your test on my pc:

**C** **agv**: ~14 seconds
```bash
max@kali:~/TEST% ./TEST 
time - 14.533836
max@kali:~/TEST% ./TEST
time - 14.329245
```

**Python agv:** ~20 seconds
```bash
>>> test()
Took:  20.4696681499
>>> test()
Took:  20.8954749107
>>> test()
Took:  19.7919199467
>>> test()
Took:  20.4452209473
>>> test()
Took:  19.8208999634
```

**Comment by serpulga** [comment]
@Mephistophiles 
Thanks for taking your time to check this.
I'm going to review my tests.

**Comment by akheron** [comment]
My test results:

**Jansson**: 7.6
**Python 3.4**: 8.0
**Python 2.7**: 9.6

Note that the Python JSON parser is also mostly written in C, so I'm not surprised that it's quite fast.

**Comment by akheron** [comment]
Forgot to say: For the test to be more fair, I changed the C test code to use `gettimeofday()` instead of `clock()` because, in my understanding, `clock()` returns used CPU time and Python's `time()` returns wall clock time.

**Comment by akheron** [comment]
For comparison between different C/C++ implementations (including Jansson), see https://github.com/miloyip/nativejson-benchmark
