### ISSUE TITLE
[Feature Request] Can you provide a function similar to json_object_set_new for json_object_update

### ISSUE THREAD

**Issue by konnanl** [akheron/jansson#281]
Cannot you provide a function json_object_update_new(json_t *object, json_t *other), This is useful when "other" is newly created and not used after the call. Thanks.

**Comment by akheron** [comment]
Yeah, why not. What about json_object_update_existing or json_object_update_missing?

**Comment by konnanl** [comment]
Sure, It should be also useful, but I seldom use _existing and _missing function =]
json_object_update_existing_new and json_object_update_missing_new should be the func name, right?

**Comment by akheron** [comment]
Yes.

**Comment by kennykwok** [comment]
When will the function be available?
The request is good, and it is almost a year after but we didn't saw them in recent release, still.

The code should be as simple as:

int json_object_update_new(json_t *object, json_t *other)
{
        int ret = json_object_update(object, other);
        json_decref(other);
        return ret;
}
