### ISSUE TITLE
how can I put a blank into a json file ?

### ISSUE THREAD

**Issue by truelv** [akheron/jansson#291]
languge: C    

My struct has a element which is empty. When I use Function: json_object_set_new , I can find it has be one element of the object ,but when I use Function : json_dump_file , I can not write in anymore,the json file like this : {"spid":"20151010","version":"1.0","uid":"138533612","epgid":"100963",balance:""    , You can see it isn't complete, I use some of the flags,but can not work. Can you help me ? Thanks.

**Comment by akheron** [comment]
I don't undestand your question. Please ask in the [jansson-users group](https://groups.google.com/forum/#!forum/jansson-users) instead of filing an issue.
