### ISSUE TITLE
json_get_real() not accept an interger 

### ISSUE THREAD

**Issue by alanywlee** [akheron/jansson#294]
Given an input json string:  {"a":1,"b":-2}

In case of trying to call 
json_get_real(root, "b", dVal) will returned 
"error: b is not a real type"

currently, I can only work around by 
        if( json_get_real(root, "b", dVal) ){
          b = dVal;
        }
        else if( json_get_integer(root, "B", nVal) ){
          b = (float)nVal;
        }

since b is real in most of the time, but input json might encode -2.0 just only to be -2,

Does it resonable to allow json_get_real() to work in case of interger?

**Comment by alanywlee** [comment]
please just ignore it, I forget json_get_real() is my wrapper function, json_real_value() work for both real and integer input

**Comment by f2404** [comment]
@alanywlee So you can close the issue.
