### ISSUE TITLE
CMake+VSC2015 'snprintf': macro redefinition fails the build

### ISSUE THREAD

**Issue by tsieprawski** [akheron/jansson#296]
While building on Windows 10 using CMake 3.3 and Visual Studio Community 2015, build fails because of snprintf redefinition in generated jansson_private_config.h.

Lines 52-54:
`#ifndef HAVE_SNPRINTF`
`#  define snprintf `
`#endif`

If you remove these, build passes.

Log after RMB on INSTALL target > Build: [build-INSTALL.txt](https://github.com/akheron/jansson/files/383350/build-INSTALL.txt)
Log after clicking Generate in CMake-GUI: [cmakegui.txt](https://github.com/akheron/jansson/files/383349/cmakegui.txt)

**Comment by tsieprawski** [comment]
[CMakeCache.txt](https://github.com/akheron/jansson/files/383357/CMakeCache.txt)

**Comment by akheron** [comment]
Have you tried with the master branch? Should be fixed already.
