### ISSUE TITLE
Should #if HAVE_STDINT_H in hashtable.c be #ifdef instead?

### ISSUE THREAD

**Issue by daviddyao** [akheron/jansson#299]
It looks like all other checks for `HAVE_STDINT_H` is with `#ifdef` so should **hashtable.c** be the same?
Same with `HAVE_CONFIG_H`.

**Comment by akheron** [comment]
It doesn't matter. If the feature is available, it's defined as `#define HAVE_STDINT_H 1`. Otherwise, it's `#undef HAVE_STDINT_H`.
