### ISSUE TITLE
Type of json_error_t's position field is int, not size_t

### ISSUE THREAD

**Issue by edmonds** [akheron/jansson#300]
Hi,

According to the documentation (https://jansson.readthedocs.io/en/2.7/apiref.html#error-reporting), the type of the `json_error_t`'s `position` field is `size_t`:

```rst
   .. member:: size_t position

      The position in bytes from the start of the input. This is
      useful for debugging Unicode encoding problems.
```

But, according to the source (https://github.com/akheron/jansson/blob/v2.7/src/jansson.h#L124), the type of this field is actually `int`.

**Comment by akheron** [comment]
Fixed, thanks!
