### ISSUE TITLE
How to extract value from string array?

### ISSUE THREAD

**Issue by alanywlee** [akheron/jansson#308]
The following example json string was successfully validated using http://jsonlint.com/

------------
{
    "a":"people",
    "b":["human","man"]
}

------------

I used following code trying to extract string values from string array "b"
on latest jansson library version (2.9)

------------
root = json_loads(json, 0, &error);
json_t *obj= json_object_get(root, "b");
for(int i = 0; i< json_array_size(obj); i++){
    json_t *obj_txt = json_array_get(obj, i);
    if( NULL==obj_txt || !json_is_string(obj_txt) ) continue;
    strText = json_string_value(obj_txt);
}

------------

However, json_is_string(obj_txt) always returned false.
In case of skip checking, json_string_value(obj_txt) returned NULL.

I wondered maybe I didn't correctly use API to decode string array.
Any suggestion is highly appreciated...

Best regards,

Alan

**Comment by akheron** [comment]
Here's a program I used to test, based on your example:
```c
#include <jansson.h>

int main() {
    json_error_t error;
    json_t *root, *obj;
    int i;
    const char *json_text = "{\"a\":\"people\",\"b\":[\"human\",\"man\"]}";

    root = json_loads(json_text, 0, &error);
    obj = json_object_get(root, "b");
    for(int i = 0; i< json_array_size(obj); i++){
        const char *strText;
	json_t *obj_txt;

        obj_txt = json_array_get(obj, i);
	if( NULL==obj_txt || !json_is_string(obj_txt) ) continue;
	strText = json_string_value(obj_txt);
	printf("found %s\n", strText);
    }
    return 0;
}
```

For me it works and prints what you would expect:
```
found human
found man
```
