### ISSUE TITLE
Is it possible to sort keys in json_object

### ISSUE THREAD

**Issue by ankithherle** [akheron/jansson#317]
I am using jansson library to create nested JSON data structure.
But I am not able to sort the keys of json object. Is it possible to sort a JSON Object according to keys after creation ?

Note: I am not using `json_dumps` or `json_loads`. I have to create nested DS using `json_object_set*` functions.

**Comment by akheron** [comment]
In Jansson 2.8 and later, the insertion of object keys is preserved. If you can construct your data structure in such a way that you insert the items in the correct order, then you're done. You can also do this in a separate step, taking an object, sorting its keys, and creating a new object with the keys in the correct order.

**Comment by ankithherle** [comment]
@akheron 

> You can also do this in a separate step, taking an object, sorting its keys, and creating a new object with the keys in the correct order.
How to do this ? Can you provide a simple example ?

**Comment by akheron** [comment]
Adapted from how `json_dumps()` and friends implement `JSON_SORT_KEYS` encoding flag (around line 300 in `src/dump.c`):

```c
/* A helper to sort strings lexically/alphabetically */
static int sort_lexically(const void *key1, const void *key2) {
    return strcmp(*(const char **)key1, *(const char **)key2);
}

json_t *sort_object(json_t *object) {
    const char **keys;
    size_t size, i;
    json_t *result;

    /* Collect object keys to the `keys` array */
    size = json_object_size(object);
    keys = malloc(size * sizeof(const char *));
    if(!keys)
        return NULL;

    i = 0;
    while(iter)
    {
        keys[i] = json_object_iter_key(iter);
        iter = json_object_iter_next(object, iter);
        i++;
    }
    assert(i == size);

    /* Sort the `keys` array. qsort() is a standard library
     * function. */
    qsort(keys, size, sizeof(const char *), sort_lexically);

    /* Iterate through the now sorted `keys` and insert values from
       `object` to `result` in that order */
    result = json_object();
    for(i = 0; i < size; i++) {
        const char *key;
        json_t *value;

        key = keys[i];
        value = json_object_get(object, key);
        assert(value);

        json_object_set(result, key, value);
    }

    /* Returns a new reference */
    return result;
}
```

I didn't even try to compile this, so it may have errors. But I hope you get the idea :)

**Comment by ankithherle** [comment]
@akheron Thanks.
I will check this.
