### ISSUE TITLE
configure: error: cannot find install-sh or install.sh in . "."/.

### ISSUE THREAD

**Issue by simplesunny** [akheron/jansson#322]
/usr/src/jansson> ./configure -prefix=/usr/
getting below error 
configure: error: cannot find install-sh or install.sh in . "."/.

Any suggestion

**Comment by akheron** [comment]
Are you compiling from a source tarball or from git?

BTW, to set the prefix, use `--prefix=/usr/`.

**Comment by Radagan** [comment]
I get the same error trying to build on Raspberry Pi 3+, but the error for me was before that with autoreconfig:
``
$ autoreconf -i
configure.ac:12: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
``
All I've done is clone the repo.

**Comment by coreyfarrell** [comment]
I'm closing this as it does not contain information required to triage and no response has been received.  @simplesunny, if you can provide details about the steps which lead to the error you can comment and we can reopen.
