### ISSUE TITLE
json string containing bracket

### ISSUE THREAD

**Issue by vdeters** [akheron/jansson#325]
Using 2.7, we see a failure when passing this text to json_loads():
[
[{"id": 13, "text": "peter ["}],
[{"id": 14, "text": "paul"}]
]

The error is:
text: end of file expected near ','
source: <string>
line: 1
column: 32
position: 32

I assume this is due to the '[' in "peter [". Is this not valid json?

Thanks,
Vince

**Comment by akheron** [comment]
Cannot reproduce on neither 2.7 nor current master. Could you post some code that reproduces the problem?

**Comment by vdeters** [comment]
Sorry for the noise, the issue was in our calling code.

**Comment by akheron** [comment]
No problem :)
