### ISSUE TITLE
super high memory usage

### ISSUE THREAD

**Issue by mrexodia** [akheron/jansson#332]
I am testing on [test_mini.json](https://mega.nz/#!js5mmaiZ!7C9lG-8Ok95OOH7hsmuafXPrJ0EsEE6tnrsQJY4fdmo) which is a minified JSON file of 76.3mb in size. Here is my code:

```c++
#include "jansson/jansson.h"

#pragma comment(lib, "jansson\\jansson_x86.lib")

static size_t memPool = 0, allocs = 0, frees = 0;

static void* json_malloc(size_t size)
{
    auto ptr = (size_t*)malloc(size + sizeof(size_t));
    *ptr = size;
    memPool += size;
    allocs++;
    return ptr + 1;
}

static void json_free(void* ptr)
{
    auto sptr = (size_t*)ptr;
    sptr--;
    memPool -= *sptr;
    frees++;
    free(sptr);
}

int main()
{
    json_set_alloc_funcs(json_malloc, json_free);
    auto json = json_load_file("test.json", 0, 0);
    printf("json: %p, memPool: %u bytes, allocs: %u, frees: %u\n", json, memPool, allocs, frees);
    getchar();
    json_decref(json);
    printf("json: %p, memPool: %u bytes, allocs: %u, frees: %u\n", json, memPool, allocs, frees);
    getchar();
}
```

The output is:

```
json: 00F638B4, memPool: 433354626 bytes, allocs: 19975350, frees: 4448313
json: 00F638B4, memPool: 0 bytes, allocs: 19975350, frees: 19975350
```

For some reason jansson wants `413.3mb` of memory(!) which is is `5.4` times the size of the file.

When removing the `size_t` overhead from the allocation (comment out `json_set_alloc_funcs`) the actual memory usage reported by Windows is `553.8mb` (`76.3+413.3=489.6`, the rest is probably runtime).

![mem usage](https://i.imgur.com/HaaSuOq.png)

Is there a way around this?

**Comment by sopvop** [comment]
To support nice dom-like api you have to have some overhead.

Size of the file says nothing about amount of nodes it will require. If said file is only one string then overhead would be just a ref-counter, `char*` and `size_t`.

But if you have a complex structure with small nodes, like tiny ints, then overhead adds up.
Jansson tries to provide nice dom-like API with reasonable speed. 

If you want to minimize overhead, then you should probably use library with sax-like api.

**Comment by mrexodia** [comment]
Okay thanks! I checked with [rapidjson](https://github.com/miloyip/rapidjson) which also provides a full DOM and there the memory usage is `238.9mb` (excluding the size of the input file). I will do some more research on what is the best solution for me. I basically only use JSON as a serialization format so probably I don't need a full DOM...

**Comment by coreyfarrell** [comment]
This does not surprise me, the JSON file you referenced has a large number of JSON objects.  Each JSON object includes a hash table for lookup of members where rapidjson appears to not use a hashtable.  This is a trade-off, hash table provides for faster lookup (read) from JSON objects, but uses more memory.  The benefit to hash tables is greater for larger objects, so rapidjson CPU performance might degrade if working with objects that have hundreds of members but the benefit is likely small for objects with only a couple members.

I don't think this is something that can be solved.

**Comment by mrexodia** [comment]
I have already solved this problem, just didn’t have time/motivation to
implement it...

The solution is to use a sax style api for reading/writing the json files.
This works because the json objects are never actually used while x64dbg is
running.

**Comment by mrexodia** [comment]
Oh I misread the email and didn't realize this was actually an issue in jansson. This issue probably hasn't been fixed, I just plan to no longer use jansson for my json parsing.
