### ISSUE TITLE
Invalid check for LONG_LONG_INT

### ISSUE THREAD

**Issue by Mephistophiles** [akheron/jansson#333]
check for
```c
if (HAVE_LONG_LONG_INT AND ((${LONG_LONG_INT}) EQUAL 8))
```
failed

but
```c
message(STATUS "LONG_LONG_INT - ${LONG_LONG_INT}")
```
returned
```
-- LONG_LONG_INT - 8
```
If I delete parentheses around LONG_LONG_INT - check works

System:

Debian 8.7 32bit - sandbox 
archlinux 64bit - host

sandbox marked by debootstrap && chroot

**Comment by akheron** [comment]
Fixed, thanks.

**Comment by Mephistophiles** [comment]
Thank you!
