### ISSUE TITLE
[feature request] Add support for hex values in json_pack() fmt specifier

### ISSUE THREAD

**Issue by sububack** [akheron/jansson#334]
We have support for strings and integer, but don't have support for parsing hex values as is without converting to integer.

**Comment by akheron** [comment]
Do you have a specific use case in mind for this functionality?

**Comment by sububack** [comment]
we use json_pack to convert raw data to json objects and we pass different values (types) read from different context. Few instances we read data from register/memory in hexadecimal format. While integer/float/string are natively supported by json_pack() which is use-full in day-to-day activity, hexadecimal is missing. As our data is mixture of all these types without hexadecimal support we are not able to use jansson part of our application. Adding this support will help users like us.

**Comment by akheron** [comment]
Closing after discussion on jansson-users: https://groups.google.com/forum/#!topic/jansson-users/waABvuBCll8
