### ISSUE TITLE
Link error undefined ref to 'pipe' when building w/ MinGW Windows

### ISSUE THREAD

**Issue by greatwolf** [akheron/jansson#338]
I get the following cmake output when building the 'test_dump' target:

    Scanning dependencies of target test_dump
    [ 92%] Building C object CMakeFiles/test_dump.dir/test/suites/api/test_dump.c.obj
    G:\OSS\jansson\test\suites\api\test_dump.c: In function 'dumpfd':
    G:\OSS\jansson\test\suites\api\test_dump.c:259:5: warning: implicit declaration
    of function 'pipe' [-Wimplicit-function-declaration]
         if(pipe(fds))
         ^
    [100%] Linking C executable bin\test_dump.exe
    CMakeFiles\test_dump.dir/objects.a(test_dump.c.obj):test_dump.c:(.text+0x1273):
    undefined reference to `pipe'
    collect2.exe: error: ld returned 1 exit status
    CMakeFiles\test_dump.dir\build.make:97: recipe for target 'bin/test_dump.exe' failed
    mingw32-make[3]: *** [bin/test_dump.exe] Error 1
    CMakeFiles\Makefile2:251: recipe for target 'CMakeFiles/test_dump.dir/all' failed
    mingw32-make[2]: *** [CMakeFiles/test_dump.dir/all] Error 2
    CMakeFiles\Makefile2:263: recipe for target 'CMakeFiles/test_dump.dir/rule' failed
    mingw32-make[1]: *** [CMakeFiles/test_dump.dir/rule] Error 2
    Makefile:237: recipe for target 'test_dump' failed
    mingw32-make: *** [test_dump] Error 2

Here's the commit that introduced this, https://github.com/akheron/jansson/commit/1672bb5a65b711d84c8adb12144bb997a4da02d4#diff-f019ac10a609124056ae8528dab25c6bR259. It looks like `unistd.h` from mingw doesn't have `pipe` defined.

**Comment by akheron** [comment]
This patch fixes the build issue on MinGW:

```diff
diff --git a/test/suites/api/test_dump.c b/test/suites/api/test_dump.c
index 17c495a..044fe72 100644
--- a/test/suites/api/test_dump.c
+++ b/test/suites/api/test_dump.c
@@ -252,7 +252,7 @@ static void dumpb()
 
 static void dumpfd()
 {
-#ifdef HAVE_UNISTD_H
+#if defined(HAVE_UNISTD_H) && !defined(__MINGW32__)
     int fds[2] = {-1, -1};
     json_t *a, *b;
 
```

I don't have a MinGW environment installed myself, but with the above patch and some modifications to appveyor.yml I was able to get the test suite run on MinGW on AppVeyor.

However, many tests seem to fail. If you want Jansson to support MinGW, you can try to make required changes for the tests to pass and submit a pull request, but unfortunately I don't have the time to try it.
