### ISSUE TITLE
json_dump function returns null when called in a function.

### ISSUE THREAD

**Issue by shuganthan** [akheron/jansson#342]
Hi ,

I need to encode some data to a json string.
It works if i do encode in main.
If i encode json in a function it stops working and json_dumps() returns NULL.

When stepped through , i found json_dumps calls strbuffer_init. 
strbuff->value = jsonp_malloc(strbuff->size);
    if(!strbuff->value)
        return -1;
strbuff->value is equal to zero and hence it returns -1 but the jsonp_malloc returns a pointer to a buffer and it is a success. 
Note:
Returns -1 when i call json_dumps from a c function . When i call from main it works perfectly.

Not able to understand why it works this way. Any inputs would be of great help.

I am using Jansson 2.7.0 ( Keil micro vision Jansson pack)

Not working 
============
void generate_json()
{
    char *s = NULL;
    int len;
    json_t* js = json_object();
    json_object_set_new( js, "SerialNumber",  json_string( SERIAL_NUMBER ) );
    json_object_set_new( js, "ProductID",     json_string(PRODUCTID) );
    json_object_set_new( js, "HWVersion",     json_string(HWVERSION));
   s = json_dumps(js,0 );  returns NULL
 
}
main()
{
     generate_json();
}

Working
=====
int main()
{
    char *s = NULL;
    int len;
    json_t* js = json_object();
    json_object_set_new( js, "SerialNumber",  json_string( SERIAL_NUMBER ) );
    json_object_set_new( js, "ProductID",     json_string(PRODUCTID) );
    json_object_set_new( js, "HWVersion",     json_string(HWVERSION));
   s = json_dumps(js,0 );  returns NULL
 
}

**Comment by shuganthan** [comment]
Hi ,

The json object has a json array when json_dumps is called from a c function whereas when json_dumps is called from main does not have a json_array.

When the json_array removed from json object it is working on both cases ( main, c function )

Not an issue.

**Comment by ndesktop** [comment]
`#include <stdio.h>
#include "jansson.h"
static const char* SERIAL_NUMBER = "SN57";
static const char* PRODUCTID = "VER00";
static const char* HWVERSION = "HW01";
static const char* SWVERSION = "SW02";

void jansson__test_2()
{
    char* s = NULL;
    int len;
    json_t* js = json_object();
    json_object_set_new( js, "SerialNumber", json_string( SERIAL_NUMBER ) );
    json_object_set_new( js, "ProductID", json_string(PRODUCTID) );
    json_object_set_new( js, "HWVersion", json_string(HWVERSION));
    s = json_dumps(js, 0); 
    if(s != NULL) {
        fprintf(stdout, "%s\n", s);
        json_free(s);
    }
    else {
        fprintf(stdout, "ERR: s is NULL\n");
    }
}

int main(int argc, char** argv)
{
    jansson__test_2();
    return 0;
}
`

Works fine with VS2015.
