### ISSUE TITLE
Is json_dumpf() atomic?

### ISSUE THREAD

**Issue by ronakg** [akheron/jansson#345]
Hi,

I'm using `json_dumpf()` to write json output to `stdout`. When this is done by multiple threads simultaneously, the output gets interleaved on `stdout`. Is it possible to make `json_dumpf()` atomic?

**Comment by Mephistophiles** [comment]
Hi. json_dumpf is not atomic. Use json_dumps and printf Use json_dumps and printf instead.

**Comment by ronakg** [comment]
Thanks.
