### ISSUE TITLE
json core!!!

### ISSUE THREAD

**Issue by ygm521** [akheron/jansson#348]
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.132.el6.x86_64 keyutils-libs-1.4-4.el6.x86_64 krb5-libs-1.10.3-10.el6_4.6.x86_64 libattr-2.4.44-7.el6.x86_64 libcap-2.16-5.5.el6.x86_64 libcom_err-1.41.12-18.el6.x86_64 libgcc-4.4.7-4.el6.x86_64 libselinux-2.0.94-5.3.el6_4.1.x86_64 libuuid-2.17.2-12.14.el6.x86_64 nss-softokn-freebl-3.14.3-9.el6.x86_64 openssl-1.0.1e-15.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  hashtable_do_rehash (hashtable=0x7faad80dd3e0, key=0x4110fe "domain", serial=8, value=0x7faad80ad2f0) at hashtable.c:175
#1  hashtable_set (hashtable=0x7faad80dd3e0, key=0x4110fe "domain", serial=8, value=0x7faad80ad2f0) at hashtable.c:219
#2  0x00007faaff9e8f0b in json_object_set_new_nocheck (json=<value optimized out>, key=<value optimized out>, value=0x7faad80ad2f0) at value.c:116

**Comment by harkue** [comment]
It looks like lack of some debug tools.
