### ISSUE TITLE
Should hashsize macro in lookup3.h be modified

### ISSUE THREAD

**Issue by GatoRat** [akheron/jansson#349]
With Visual Studio 2015 64-bit, I'm getting C4334 warnings (result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?) The culprit is hashsize in lookup3.h.

My immediate thought is to change the line (75) from:

`#define hashsize(n) ((uint32_t)1<<(n))`

to

`#define hashsize(n) ((size_t)1<<(n))`

But I'm not sure if that would cause other issues. Any thoughts?

**Comment by akheron** [comment]
That should work. The `lookup3` algorithm was not written by me, and it seems that the author intended the result of the `hashsize()` macro to be used with `uint32_t` instead of `size_t`.

**Comment by akheron** [comment]
Instead of modifying `lookup3.h`, you could also cast the result of `hashsize()` to `size_t` explicitly in `hashtable.c` everywhere it's used.

**Comment by MortenBroerup** [comment]
This was fixed with commit 38c4b80ab70aaa9fbc3d728959083ddff9132b6e.
