### ISSUE TITLE
Issues while used with legato application framework

### ISSUE THREAD

**Issue by WedaPashi10** [akheron/jansson#367]
I tried using this with legato application framework.

It gives an error:

`/usr/local/lib/libjansson.so:` file not recognized: File format not recognized`

My interpretation of the issue is, is the problem with not cross-compiling libjansson? I have compiled Jansson straight and simple, do I have to build it with any considerations for legato?
The documentation for Jansson has a CMake section, which says,

> By default the CMake project will generate build files for building the static library. To build the shared version use: cmake -DJANSSON_BUILD_SHARED_LIBS=1

I have done this step.

Host machine is ubuntu16.04 LTS, 64-bit.

I have tried a simple hello world C program, and compiled it using
`gcc -o HelloWorld hello.c -ljansson`
without any issues.

Is there anything else specific to legato?

**Comment by akheron** [comment]
I don't know anything about Legato, but many embedded frameworks/build tools make it easy to cross compile projects that use Autoconf. Passing the correct flags to `./configure` does the trick.
