### ISSUE TITLE
json_dump_callback: Document whether the chunks passed to the callback are valid UTF-8

### ISSUE THREAD

**Issue by phst** [akheron/jansson#369]
It seems that the chunks passed to `json_callback_t` are always valid UTF-8 strings (assuming the strings in the JSON object are valid UTF-8), but this isn't documented in https://jansson.readthedocs.io/en/latest/apiref.html#c.json_dump_callback_t. Would be nice to document to clarify what callback implementers should expect.

**Comment by phst** [comment]
Similarly, https://jansson.readthedocs.io/en/latest/apiref.html#c.json_load_callback_t should specify whether the copied chunk has to be valid UTF-8, or whether it's enough for the concatenated string to be UTF-8.

**Comment by akheron** [comment]
Could you open a PR?

**Comment by phst** [comment]
Sure, but I'd need to know the answers to the questions first ;)

**Comment by akheron** [comment]
The callback passed to `json_dump_callback` always gets valid UTF-8, as you already figured out.

The decoder handlers input byte by byte, so the data provided by the callback to `json_load_callback` doesn't need to break on code point boundaries.

**Comment by phst** [comment]
Thanks, that looks like a great example of the Postel principle. Will send a PR.
