### ISSUE TITLE
Test-cases use stack variables instead of heap variables

### ISSUE THREAD

**Issue by markhermelinggt** [akheron/jansson#371]
This pattern is repeated in a number of test case, like
jansson/test/suites/api/test_equal.c, for example in test_equal_simple

On line 18. The test-case creates a json_true instance using:
value1 = json_true();

But json_true is:
from jansson/src/value.c:906:
 json_t *json_true(void)
 {
 static json_t the_true = {JSON_TRUE, (size_t)-1};
 return &the_true;
}

After doing a few tests test_equal_simple does:
   json_decref(value1);

Which leads to 
    (*do_free)(ptr);
in jansson/src/memory.c line 36.

This is freeing a non-heap variable.

Found this doing static analysis. 

[Free Non-Heap Variable : jansson : CodeSonar.pdf](https://github.com/akheron/jansson/files/1436855/Free.Non-Heap.Variable.jansson.CodeSonar.pdf)

**Comment by Mephistophiles** [comment]
Nope, for json bool ref count is -1.

json_decref:
void json_decref(json_t *json)
{
    if(json && json->refcount != (size_t)-1 && --json->refcount == 0)
        json_delete(json);
}

**Comment by markhermelinggt** [comment]
I stand corrected, thanks!
