### ISSUE TITLE
Adding a maximum level of nesting for JSON parsing to avoid crash

### ISSUE THREAD

**Issue by babelouest** [akheron/jansson#372]
It seems that the functions `json_load*` don't have a way to specify a maximum nesting level.
This could lead to a program crash if a string containing a large level of nested arrays for example is parsed by Jansson.

Someone made some tests with different JSON libraries and published the results he found: https://github.com/lovasoa/bad_json_parsers
The result is not eloquent by itself, because it depends on the program, the machine and the context, but there is a limit to the nesting level Jansson decoder can handle, whatever the conditions are.

I haven't seen a solution to avoid this in Jansson documentation.

A possible solution could be to add a flag in the decoding functions, for example `JSON_DECODE_NESTING_MAX(x)` where `x` is a positive integer.

**Comment by phst** [comment]
If we want to spend more effort on this, we could also switch to explicit stack management without recursion.

**Comment by babelouest** [comment]
Switching to explicit stack management instead of recursion could help to increase the maximum nesting level but the problem would still remain.

I suppose that explicit stack management can be implemented in parallel of a new decoding flag.

**Comment by akheron** [comment]
This has already been fixed, see #282, #284.

**Comment by babelouest** [comment]
Cool, thanks for the precision
