### ISSUE TITLE
Typo in check_include_files() affecting HAVE_SYS_TYPES_H macro definition.

### ISSUE THREAD

**Issue by phniix** [akheron/jansson#373]
Hi,

The following line appears to be a typo in CMakeLists.txt:

https://github.com/akheron/jansson/blob/9e7847ed261636b5a505cbc9be52946f7d668724/CMakeLists.txt#L141

I suspect the instruction should actually read to be the following:
```
check_include_files (sys/types.h HAVE_SYS_TYPES_H)
```

Am I correct in my suspicion ?

**Comment by akheron** [comment]
I think you are. Could you fix it an open a PR?

**Comment by phniix** [comment]
Yeah mate, no dramas.
