### ISSUE TITLE
Need help to build a static or shared libraries for  Android arch x86, arm64-v8a and armeabi-v7a

### ISSUE THREAD

**Issue by chowdarynamala** [akheron/jansson#379]
Hi All,

I am new to using this library. I tried building static library(.a file) and integrating the same into my Android project from Android.mk file. But when I run ndk-build I am getting the error
/home/ddlg/Lakshmi/android-ndk-r12b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: jni/../../../libs/jansson/libjansson.a(value.c.o): Relocations in generic ELF (EM: 62)
jni/../../../libs/jansson/libjansson.a: error adding symbols: File in wrong format

My Application.mk has following 
APP_STL := gnustl_static
APP_ABI := arm64-v8a armeabi-v7a x86

I have defined the static library in Android.mk as below
# JANSSON
include $(CLEAR_VARS)
LOCAL_MODULE := JANSSON
LOCAL_SRC_FILES := $(JANSSON_LIB_PATH)/libjansson.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/$(JANSSON_LIB_PATH)/include
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE    := VoIPCore
LOCAL_STATIC_LIBRARIES := JANSSON
LOCAL_LDLIBS := -L$(SYSROOT)/usr/lib -L$(JANSSON_LIB_PATH) -llog
LOCAL_CPPFLAGS  := -std=gnu++11 -ljansson

**Comment by Mephistophiles** [comment]
Jansson builded with target cc?

**Comment by chowdarynamala** [comment]
@Mephistophiles  Thanks for the reply. I am doing following steps to build the static library
1. git clone https://github.com/akheron/jansson.git
2. cd jansson
3. autoreconf -i
4. ./configure
5. mkdir build
6. cd build
7. cmake ..
8. make

After this I copied the generated .a and include directory to my project and trying to use.

Please let me know if anything I need to do in between the above steps

**Comment by Mephistophiles** [comment]
you must use the crosscompiler for arm. Configure env CC="path to arm gcc" ./configure

**Comment by chowdarynamala** [comment]
Thank you @Mephistophiles  I will try this out and update.

**Comment by chowdarynamala** [comment]
@Mephistophiles  I have used the crosscompiler to generate the static library. But still I see the same issue as in my original post. Can you please guide me whether the approach that I am using the static library as I gave in Android.mk file is correct?

**Comment by chowdarynamala** [comment]
I resolved the issue after including the build procedure into my project Android.mk file.

Thanks @Mephistophiles
