### ISSUE TITLE
Use atomic built-ins to change json->refcount.

### ISSUE THREAD

**Issue by coreyfarrell** [akheron/jansson#387]
I would like to make `json_decref` / `json_incref` thread safe.  This would allow use of a single JSON object from multiple threads as long as the object were not manipulated (no adding/removing object fields or array elements).  For my use Asterisk PBX will be able to reduce jansson memory usage by bumping the reference instead of cloning the object.

A couple questions:
* Are the existing configure.ac tests adequate or do we need to check for every __sync / __atomic function we use?
* Do we need to move json_decref / json_incref to value.c and lose inlining or add results of the __sync / __atomic tests to jansson_config.h?  Keeping it in the header would create a requirement that programs using jansson use a compiler that supports the atomic feature specified by jansson_config.h.

**Comment by akheron** [comment]
This is an interesting idea!

Answers & comments:

- `configure.ac` and `CMakeLists.txt` check for `__sync_bool_compare_and_swap` and `__atomic_test_and_set/__atomic_store_n/__atomic_load_n`. More tests can be added if needed.

- I don't see why `json_decref` or `json_incref` would have to live in value.c. The `#ifdef`s that guard for __sync/__atomic support should be added to `jansson_config.h.in`/`jansson_config.h.cmake` and could also be used in `jansson.h`.

- If "read-only" thread safety like this is supported, the info should be available to users via a `JANSSON_*` typedef.

- Also keep in mind that encoding functions (`json_dumps` et al.) are not thread safe at the moment: they detect circular references by setting the `visited` flag on arrays and objects.

- You would also have to make sure that malloc and free are thread safe, but I guess that already is the case when your program is threaded.

**Comment by coreyfarrell** [comment]
> If "read-only" thread safety like this is supported, the info should be available to users via a JANSSON_* typedef.

I'm not sure I fully understand this comment.  I've added `#define` statements to jansson_config.h.in.

I've also added the ability for programs to provide a replacement for unsafe reference handling (only used if the compiler doesn't support __sync or __atomic).
