### ISSUE TITLE
Add Binary Load/Dump Support

### ISSUE THREAD

**Issue by dleeds-cpi** [akheron/jansson#388]
This is a feature recommendation, not a bug.  BSON or MessagePack as an alternative data encoding would provide better data compression and performance than string-encoded JSON.  It is ideal to add binary support to Jansson, since it is already a/the leading C JSON library, and the user-base and community would immediately take advantage of it.

* A family of binary dump and load functions would be added to write and parse binary encoded JSON.
* BSON and MessagePack specifications include some additional encoding types for things like timestamps.  Only the data types already supported by Jansson would need to be implemented.

**Comment by akheron** [comment]
I'd like to keep the Jansson "core" purely a JSON library. It should be possible to do binary encoding/decoding as separate projects, e.g. `jansson-bson` or `jansson-msgpack`, which would depend on Jansson and use Jansson's data model.
