### ISSUE TITLE
I do not know if the memory need be freed

### ISSUE THREAD

**Issue by enjoydiy** [akheron/jansson#390]
such as json_unpack, get a string var, Do I need free the string var?
Your document do not refer to whether free memory.

**Comment by akheron** [comment]
No, you don't need to free it. From [the documentation](http://jansson.readthedocs.io/en/2.10/apiref.html#parsing-and-validating-values) of the `s` format specifier:

> Convert a JSON string to a pointer to a null terminated UTF-8 string. The resulting string is extracted by using json_string_value() internally, so it exists as long as there are still references to the corresponding JSON string.

Maybe this is not 100 % clear, but it tries to say that the memory is managed by the `json_t` string value, and is freed when the `json_t` is freed.
