### ISSUE TITLE
size_t name conflict in jansson.h

### ISSUE THREAD

**Issue by openGLnoob** [akheron/jansson#391]
Hi there!
I try to use Jansson in MSVC2013 and I can't resolve a name conflict of size_t in jansson. For example any size_t in jansson.h points on this typedef below and doesn't see size_t in crtdefs.h.

> typedef size_t (*json_load_callback_t)(void *buffer, size_t buflen, void *data);//ERROR: "function returning function is not allowed"

>json_t *json_loads(const char *input, size_t flags, json_error_t *error); //size_t points on declaration above.

**Comment by akheron** [comment]
I'm not an expert on MSVC, but Jansson is built tested on Visual Studio 12 2013 by Appveyor CI, and everything works fine. The build config is here:

https://github.com/akheron/jansson/blob/9e5af7c3b77f81a7d1720073dca600e51fe9962d/appveyor.yml

Does this help you resolve the issue?

**Comment by openGLnoob** [comment]
Sorry, my mistake was conflict of names size_t in MinGW and MSVC standart libraries included at simultaneously. It was not a problem of Jansson. :)

**Comment by openGLnoob** [comment]
Petri, one last question: how is the propper way to install Jansson in MinGW? If I install Jansson in user\local (default path), my MinGW can't find this libs when it required. Coping .libs in MinGW root is the one way?
