### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by coreyfarrell** [akheron/jansson#394]
This ticket is to ask if I can help get v2.11 released.  It contains many useful features and some bug fixes that will help make the library safer for long running and multi-threaded processes.

Are any current bugs blockers for a new release?  Can I do anything else to help?  Sorry for my lack of familiarity with your release process.

**Comment by akheron** [comment]
Hi! #395 is the only issue that blocks v2.11, and I'll merge it as soon as tests pass.

I would greatly appreciate if you could be the "release manager" of v2.11 and do the first 4 steps of this checklist https://github.com/akheron/jansson/wiki/Releasing and open a PR with those changes. You should check that your changes look similar to earlier release commits, too.

After that it's very easy for me to cut a release by tagging and making the release tarballs.

**Comment by coreyfarrell** [comment]
I've completed the first 10 steps (everything up to `git commit -m 'jansson 2.11`).  I'm sure you'll probably rerun the valgrind distcheck but it worked for me on Fedora 26.

This is my first time dealing with libtool version declarations (src/Makefile.am and CMakeLists.txt).  I think I got it right but please double-check.
