### ISSUE TITLE
Problem extracting values with simple_parse.c example

### ISSUE THREAD

**Issue by klavdio** [akheron/jansson#399]
using the whole code of simple_parse.c, and passing as json a string json verified on https://jsonlint.com (taken from a http request to google maps api), gives me an error…

a part of json:

{
   "geocoded_waypoints" : [
      {
         "geocoder_status" : "OK",
         "place_id" : "ChIJHYoaQLGb3RIRS0rdLTY3gbE",
         "types" : [ "locality", "political" ]
      },
      {
         "geocoder_status" : "OK",
         "place_id" : "ChIJoxyOthU05xIRsW6BzwYVHiA",
         "types" : [ "locality", "political" ]
      }
   ],
 "routes" : [
      {
         "bounds" : {……...
"copyrights" : "Dati mappa ©2018 Google",
"legs" : [………..
 "overview_polyline" : {……...
 "summary" : "E25",
 "warnings" : [],
 "waypoint_order" : []
 }
   ],
   "status" : "OK"
}

the error:

JSON Object of 3 pairs: 
 JSON Key: "geocoded_waypoints" 
 JSON Array of 2 elements: 
   JSON Object of 3 pairs: 
     JSON Key: "geocoder_status" 
     JSON String: "OK" 
Segmentation fault (core dumped)

**Comment by coreyfarrell** [comment]
I'm unable to reproduce this issue with the JSON you've posted.  I replaced the '.......' strings with closing `]` or `}` as appropriate.  I used `gcc -g examples/simple_parse.c src/.libs/libjansson.a -o examples/simple_parse` to build the simple_parse executable and no crash.

Please rerun your test using gdb.  Once the crash occurs run `bt full` within gdb, then post the backtrace.  In addition please confirm you are using jansson-2.11.

**Comment by klavdio** [comment]
yes, I'm using version 2.11...
i used  `gcc -g my_parse_json.c -ljansson` , and then  `gdb a.out` , then  `run`...
surprisingly, the program read all the json code without errors! why? what should I do?

**Comment by Mephistophiles** [comment]
Try run: valgrind a.out

**Comment by klavdio** [comment]
it's the same thing, I read everything without mistakes....

**Comment by klavdio** [comment]
but with `valgrind ./myfile` , the result is:

==6767== Memcheck, a memory error detector
==6767== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==6767== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==6767== Command: ./my_parse_json
==6767== 

PARSE json...
Jansson version: 2.11.0
JSON Object of 3 pairs:
  JSON Key: "geocoded_waypoints"
  JSON Array of 2 elements:
    JSON Object of 3 pairs:
      JSON Key: "geocoder_status"
      JSON String: "OK"
==6767== Use of uninitialised value of size 8
==6767==    at 0x4E3E1C3: json_object_iter_next (in /lib/x86_64-linux-gnu/libjson-c.so.2.0.0)
==6767==    by 0x401326: print_json_object (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401173: print_json_aux (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x4013DA: print_json_array (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401189: print_json_aux (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401308: print_json_object (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401173: print_json_aux (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401135: print_json (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x4017F3: main (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767== 
==6767== Invalid read of size 8
==6767==    at 0x4E3E1C3: json_object_iter_next (in /lib/x86_64-linux-gnu/libjson-c.so.2.0.0)
==6767==    by 0x401326: print_json_object (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401173: print_json_aux (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x4013DA: print_json_array (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401189: print_json_aux (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401308: print_json_object (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401173: print_json_aux (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401135: print_json (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x4017F3: main (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==  Address 0x10 is not stack'd, malloc'd or (recently) free'd
==6767== 
==6767== 
==6767== Process terminating with default action of signal 11 (SIGSEGV)
==6767==  Access not within mapped region at address 0x10
==6767==    at 0x4E3E1C3: json_object_iter_next (in /lib/x86_64-linux-gnu/libjson-c.so.2.0.0)
==6767==    by 0x401326: print_json_object (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401173: print_json_aux (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x4013DA: print_json_array (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401189: print_json_aux (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401308: print_json_object (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401173: print_json_aux (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x401135: print_json (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==    by 0x4017F3: main (in /home/claudio/Scrivania/WORKSPACE/my_parse_json-/my_parse_json)
==6767==  If you believe this happened as a result of a stack
==6767==  overflow in your program's main thread (unlikely but
==6767==  possible), you can try to increase the size of the
==6767==  main thread stack using the --main-stacksize= flag.
==6767==  The main thread stack size used in this run was 8388608.
==6767== 
==6767== HEAP SUMMARY:
==6767==     in use at exit: 58,399 bytes in 918 blocks
==6767==   total heap usage: 1,760 allocs, 842 frees, 6,659,400 bytes allocated
==6767== 
==6767== LEAK SUMMARY:
==6767==    definitely lost: 0 bytes in 0 blocks
==6767==    indirectly lost: 0 bytes in 0 blocks
==6767==      possibly lost: 0 bytes in 0 blocks
==6767==    still reachable: 58,399 bytes in 918 blocks
==6767==         suppressed: 0 bytes in 0 blocks
==6767== Rerun with --leak-check=full to see details of leaked memory
==6767== 
==6767== For counts of detected and suppressed errors, rerun with: -v
==6767== Use --track-origins=yes to see where uninitialised values come from
==6767== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
Errore di segmentazione (core dump creato)

**Comment by klavdio** [comment]
ok, fixed, or rather, found the problem in codeblocks ...if i compile with gcc on the terminal everything is ok.
I continue in this way that is safer,then later  I will try to solve the problem... thanks to everyone!
