### ISSUE TITLE
Update install instructions in README

### ISSUE THREAD

**Issue by vsoch** [akheron/jansson#401]
Are the install instructions correct? I cloned the repo and downloaded a release (both source I think?) and am not able to ./configure --> make --> install. Any help would be appreciated, thanks!

**Comment by vsoch** [comment]
ah! Found it in a link on the main page: http://www.digip.org/jansson/ 

Would that be worth linking / referencing somehow from the repo?

**Comment by akheron** [comment]
Yeah, that section could be clearer. The world has changed in these ~9 years. Back then, separate release tarballs were the common way to distribute projects (see http://www.digip.org/jansson/releases/). Nowadays people tend to clone the git repo, and in that case you need to run `autoreconf -fi`, which is mentioned a bit later in README.

**Comment by akheron** [comment]
CMake is not mentioned at all either, even though support for it was added in 2012.

**Comment by coreyfarrell** [comment]
Documenting CMake will have to be done separate by someone who is familiar with it.
