### ISSUE TITLE
BAD signature from "Petri Lehtinen <petri@digip.org>"

### ISSUE THREAD

**Issue by hdatma** [akheron/jansson#403]
gpg_verify jansson-2.11.tar.gz.asc 
gpg: assuming signed data in 'jansson-2.11.tar.gz'
gpg: Signature made Sun Feb 11 19:27:58 2018 CET
gpg:                using RSA key B5D6953E6D5059ED7ADA0F2FD3657D24D058434C
gpg: BAD signature from "Petri Lehtinen <petri@digip.org>" [unknown]

**Comment by akheron** [comment]
Cannot reproduce:
```
wget http://www.digip.org/jansson/releases/jansson-2.11.tar.{gz,gz.asc,bz2,bz2.asc}
gpg --verify jansson-2.11.tar.gz.asc
gpg --verify jansson-2.11.tar.bz2.asc
```

Both `gpg --verify` commands report good signature.
