### ISSUE TITLE
JSON Object parsing

### ISSUE THREAD

**Issue by sunilsharmap** [akheron/jansson#405]
How can I parse JSON objects?
Ex: const char * json_string = {"name": "Jansson", "properties": {"value1": 10, "value2": 20}};

json_t * root = NULL;
json_error_t error;
root = json_loads(json_string, 0, &error);
if(root) {
    printf("Key: %s Value:%s\n", json_string_value(json_object_get(root, "name"));
}
This will print Key:name  Value:Jansson

BUT, How to get the values of properties?

**Comment by Mephistophiles** [comment]
Incorrect code:
```c
printf("Key: %s Value:%s\n", json_string_value(json_object_get(root, "name"));
```
```
main.c:12:26: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
   printf("Key: %s Value:%s\n", json_string_value(json_object_get(root, "name")));
                         ~^
```

for get properties try this:
```c
json_t *properties = json_object_get(root, "properties");
int value1 = json_integer_value(json_object_get(properties, "value1"));
int value2 = json_integer_value(json_object_get(properties, "value2"));
```

**Comment by sunilsharmap** [comment]
thank you...
It was useful
