### ISSUE TITLE
Linking error: Undefined reference to 'stdin'  when compiling with android NDK r14b or higher

### ISSUE THREAD

**Issue by chraac** [akheron/jansson#413]
Since android NDK change to unified headers, the exporting of stdin has been remove.
So can we check the NDK version to preventing linking error?

Reference:
[NDK: Unified Headers issue](https://github.com/android-ndk/ndk/issues/445#issuecomment-313322546)
[Compilation fails with android ndk r15b](https://github.com/openssl/openssl/issues/3826)

**Comment by feliwir** [comment]
Compile with `no-stdio` and it'll probably work.
