### ISSUE TITLE
How to use in windows x64 bit arch application

### ISSUE THREAD

**Issue by mahmudur85** [akheron/jansson#418]
Hi,
I was trying to use jansson in a x64 arch application and its giving the following warning

> Warning	LNK4272	library machine type 'X86' conflicts with target machine type 'x64'

I was able to work it on WIN32 application.
So, Is there any way to compile it for Windows x64 bit systems?

**Comment by akheron** [comment]
Hi! The preferred way to build Jansson on Windows is CMake. Did you use it or something else?
