### ISSUE TITLE
json_loads bug!

### ISSUE THREAD

**Issue by nmodnation** [akheron/jansson#428]
json = json_loads("{\\"c\\":1,\\"score\\":2991.0}");
msgbox(json_dumps(json));

result: {"c": 1, "score": 1.0}

**Comment by coreyfarrell** [comment]
I'm not able to reproduce this error.  Worth mentioning your example code is not following the API for json_loads or json_dumps.  I used the following code to test this (I used printf as I don't know what msgbox is).

```c
#include <stdio.h>
#include <jansson.h>

int main(int argc, char *argv[])
{
	json_t *json = json_loads("{\"c\":1,\"score\":2991.0}", 0, NULL);
	printf("%s\n", json_dumps(json, 0));
	return 0;
}
```
I then compiled and ran, it produced the correct results:
```
$ gcc -ljansson test.c -o mytest && ./mytest
{"c": 1, "score": 2991.0}
```
