### ISSUE TITLE
CMAKE not totally cross-compile (fail on msys2 for windows)

### ISSUE THREAD

**Issue by CicTec** [akheron/jansson#429]
Hello,

CMake fail to generate the build on toolchain MSYS2 (https://www.msys2.org/) for windows.

Here the complete build log:
....MINGW32 /c/../json/build
$ ....MINGW32 /c/../json/build
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: C:/msys64/mingw32/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:99 (include):
  include could not find load file:

    CheckFunctionKeywords

C compiler: GNU
-- Looking for include file endian.h
-- Looking for include file endian.h - not found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file sched.h
-- Looking for include file sched.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file sys/param.h
-- Looking for include file sys/param.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for close
-- Looking for close - found
-- Looking for getpid
-- Looking for getpid - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for open
-- Looking for open - found
-- Looking for read
-- Looking for read - found
-- Looking for sched_yield
-- Looking for sched_yield - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of __int64
-- Check size of __int64 - done
-- Check size of int64_t
-- Check size of int64_t - done
-- Check size of long long
-- Check size of long long - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of __int32
-- Check size of __int32 - done
-- Check size of long
-- Check size of long - done
-- Check size of int
-- Check size of int - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of __uint32
-- Check size of __uint32 - failed
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of __uint16
-- Check size of __uint16 - failed
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of __uint8
-- Check size of __uint8 - failed
-- Check size of ssize_t
-- Check size of ssize_t - done
-- Check size of SSIZE_T
-- Check size of SSIZE_T - failed
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for strtoq
-- Looking for strtoq - not found
-- Looking for _strtoi64
-- Looking for _strtoi64 - found
-- Looking for include file locale.h
-- Looking for include file locale.h - found
-- Looking for localeconv
-- Looking for localeconv - found
-- Looking for setlocale
-- Looking for setlocale - found
CMake Error at CMakeLists.txt:285 (check_function_keywords):
  Unknown CMake command "check_function_keywords".

-- Configuring incomplete, errors occurred!
See also "C:/.../json/build/CMakeFiles/CMakeOutput.log".
See also "C:/.../json/build/CMakeFiles/CMakeError.log".

**Comment by akheron** [comment]
I'm not sure where the problem is. The relevant part of `CMakeLists.txt` is like this:
```
# for CheckFunctionKeywords
set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
# ,,,
include (CheckFunctionKeywords)
```
So the search path is set correctly before including.

**Comment by CicTec** [comment]
Hello,

Yes, seems that can't load "CheckFunctionKeywords".

I do not know if this is an unix extension, or some package to install in MSYS2 is missing, but it does not currently compile

**Comment by ploxiln** [comment]
> $ ....MINGW32 /c/../json/build

I wonder if the virtual-c-drive-folder thing, plus the ".." parent dir, confused things so cmake could not find any files. Can you post the specific steps you used up to calling cmake, including cloning or extracting the source, making a build dir, changing to the build dir, etc? Maybe if you do an in-tree build instead of an out-of-tree-build it can confirm whether the problem is related to this?

**Comment by CicTec** [comment]
Hello,

I've found the issue, cmake/CheckFunctionKeywords.cmake was badly copied and the size was 0 bytes, now the build is generated correctly.

Now I have some problems with using it in a dynamic library because jasson requires the libstdc++ library which in MSYS2 is the libstdc++6.dll library that depends on libwinpthread-1.dll and I need to link jansson and its dependencies in a static way in a dynamic library.
the stdc++ library resolves the static linking with the -static-libstdc++ linking option, the winpthread should resolve with the -lwinpthread option, however it does not seem to work and continues to require the dynamic library as a dependency.

I hope you can add the options in CMAKE for the static linking of these libraries for those using MSYS2 in windows (as in the case of the STATIC_CRT option for MSVC).

Thanks for the support.
