### ISSUE TITLE
Decref not releasing memory

### ISSUE THREAD

**Issue by yldzmuhammed** [akheron/jansson#431]
Hello.

I am working on a project with nRF52862 mcu and it is doing some thing gateway stuff.

I am creating a json and fill it with some metadata and sensor datas.

I can successfull create json object. And send it over gsm to the cloud.

Then i should update json file. But as i understand that is not possible for me.

So i am using decref function to create all over it again. 

But when i recreate second json object (which it is an array) it allocates more memory compare to the before.

Every recreate takes more memory, and then finaly hardfault exception happens. 

How can i completly delete json object?My object something like:

`{"gw_id": "A0:82:A7:6F:BD:9A:39:2B", "imei": "867521029181135", "gw_rssi": -89, "gw_bat": 4794, "periph": [{"name": "ViLE-Env", "rssi": -69, "srv": [{"s_uuid": "181A", "char": [{"uuid": "2A6D", "val": 9971.3}, {"uuid": "2A6E", "val": 28.42}, {"uuid": "2A6F", "val": 64.0}, {"uuid": "806A", "val": false}]}]}, {"name": "ViLE-Distance", "rssi": -43, "srv": [{"s_uuid": "FEFA", "char": [{"uuid": "8007", "val": 99}]}]}, {"name": "ViLE-Acc", "rssi": -64, "srv": [{"s_uuid": "FF00", "char": [{"uuid": "8000", "val": 496}, {"uuid": "8001", "val": -400}, {"uuid": "8002", "val": 7904}]}]}]}
`

**Comment by coreyfarrell** [comment]
Decref releases memory when the reference count reaches 0.  I use jansson in Asterisk PBX, if jansson had the bug as you suggest Asterisk developers would absolutely know.  It's difficult to say what you are doing wrong without seeing code.  You are failing to decref an object or you are using a 'bump reference' variant of a function where you should use a reference stealing function.

**Comment by coreyfarrell** [comment]
You are using `json_object_set` but you need to use `json_object_set_new`.  json_string() creates an object with 1 reference held, then json_object_set adds another reference.  Same goes for json_array_append, you need the `_new` variant if you want the array to steal the creation reference.

See https://jansson.readthedocs.io/en/2.11/apiref.html#c.json_object_set_new

Also take a look at `json_pack` - this function would allow you to write much more compact code.
