### ISSUE TITLE
__strtod

### ISSUE THREAD

**Issue by jwhere** [akheron/jansson#441]
gcc --version
gcc.exe (MinGW.org GCC-6.3.0-1) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gcc -DHAVE_CONFIG_H=1 -s -static-libgcc -shared -o jansson.dll *.c
strconv.c: In function 'jsonp_strtod':
strconv.c:18:16: warning: implicit declaration of function '__strtod' [-Wimplicit-function-declaration]
 #define strtod __strtod
                ^
strconv.c:77:13: note: in expansion of macro 'strtod'
     value = strtod(strbuffer->value, &end);
             ^~~~~~

------------------------------------------------------------------------------------------------------

#include <stdio.h>
#include <jansson.h>

int main(int argc, char *argv[]) {
    json_t *json = json_loads("{\"c\":1,\"score\":2991.0}", 0, NULL);
    printf("%s\n", json_dumps(json, 0));
    return 0;
}

[output]
{"c": 1, "score": 1.0}

------------------------------------------------------------------------------------------------------

solution

strconv.c:

#include <assert.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#ifdef __MINGW32__
#undef __NO_ISOCEXT /* ensure stdlib.h will declare prototypes for mingw own 'strtod' replacement, called '__strtod' */
#endif
#include "jansson_private.h"
#include "strbuffer.h"

/* need jansson_private_config.h to get the correct snprintf */
#ifdef HAVE_CONFIG_H
#include <jansson_private_config.h>
#endif

▽▽▽▽ REMOVE LINE 18 ▽▽▽▽
#ifdef __MINGW32__
#define strtod __strtod
#endif

**Comment by AllenX2018** [comment]
It reproduced. If we use __strtod, it will result in 4 of 5 test suits(about precesion) failed.

By the way, find it a note in stdlib.h written as:
```c
_CRTIMP __cdecl __MINGW_NOTHROW  double strtod (const char *, char **);
.........

#if __USE_MINGW_ANSI_STDIO
/* Microsoft's strtod() and atof() implementations, (in MSVCRT.DLL),
 * mishandle infinities and NaNs; on the basis that this conditional
 * exposes a more ISO-C conforming printf() I/O family implementaion,
 * we substitute a similarly more conforming implementation for each
 * of this pair of (somewhat related) functions.
 *
 * Note that we provide neither __JMPSTUB__ nor __LIBIMPL__ external
 * equivalents for either of these two inline functions, because they
 * would conflict with the runtime DLL implementations; users needing
 * an address reference for either must provide an equivalent of the
 * inline implementation, as non-inlined within their own code.
 */
extern __cdecl __MINGW_NOTHROW
double __strtod (const char *__restrict__, char **__restrict__);

__CRT_ALIAS __cdecl __MINGW_NOTHROW
double strtod (const char *__restrict__ __nptr, char **__restrict__ __endptr)
{ return __strtod( __nptr, __endptr ); }
........
#endif  /* __USE_MINGW_ANSI_STDIO */
```

And some refrence like: [Deprecation of __USE_MINGW_ANSI_STDIO](https://osdn.net/projects/mingw/lists/archive/users/2019-January/000202.html)

I guess, MinGW has a work around solution to fix "strtod" bug and now it has no need to do this.

So, as @nmodnation said, remove the three lines, works fine, all test passed!

**Comment by GitMensch** [comment]
Look like this was solved by merging and can be closed.
