### ISSUE TITLE
Core dumped on json_pack

### ISSUE THREAD

**Issue by Grindv1k** [akheron/jansson#444]
I am doing some automated testing using this library and came across a core dump.

A minimal example:

```c
#include <jansson.h>

int main(int argc, char const *argv[])
{
    const char json_format[6] = "[1s";
    const char json_data[10]  = "Hi";

    json_pack(json_format, json_data);

    return(0);
}
```

My terminal output is 

```
*** Error in `./bug03': munmap_chunk(): invalid pointer: 0x000000000040077a ***
Aborted (core dumped)
```

and I believe this can be traced to  `jansson/src/memory.c:36` if I've understood my tooling output correctly.

As I am doing automated testing I do not actually know your API, so you'll have to tell me if this is a real bug or a false positive (i.e. something the user simply should not do).

**Comment by coreyfarrell** [comment]
This is a bug in `pack_unpack.c:pack_string()`.  Although your format string is malformed this should not cause a segmentation fault, it should simply cause json_pack to return NULL.

json_pack format documentation: https://jansson.readthedocs.io/en/2.11/apiref.html#building-values

**Comment by ploxiln** [comment]
I'm not sure if it's practical for `json_pack()` to ensure the proper number of arguments, and their types (which is OK if the format string is always strictly controlled by the programmer, typically as just a string literal argument).

**Comment by coreyfarrell** [comment]
I said this specific case should not cause a segmentation fault.  The issue is that pack_string is incorrectly trying to free the string "Hi" which is impossible.

You are correct though we often cannot know of incorrect argument types, this is up to the programmer to perform testing/reviews on their code.
