### ISSUE TITLE
Crash when excute json_decref

### ISSUE THREAD

**Issue by StarIsCoder** [akheron/jansson#449]
Hi,
I'm working on a project using Jansson to send http request.And crash happened when build request
```
JanssonTest(84916,0x1003ac380) malloc: *** error for object 0x102858928: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

Code are as the following
```
json_t *methodParaJson = json_object();
    
tmp = request.displayName;
json_object_set_new(methodParaJson, "displayName", json_string(tmp.c_str()));
    
json_t *requestJson = wrapper(methodParaJson, "initConnection");

char *requestStr = json_dumps(requestJson, 0);
requestBody = std::string(requestStr);
    
free(requestStr);
json_decref(requestJson);

json_decref(methodParaJson);// The code cause crash


json_t *ProximityRequestBodyBuilder::wrapper(json_t *parameterJson, const std::string &methodName)
{
    json_t *root = json_object();
    
    //wrap token
    json_object_set_new(root, "token", json_string("ed2f"));
    
    //wrap method
    json_t *methodPara = json_object();
    json_object_set_new(methodPara, methodName.c_str(), parameterJson);

    //wrap request
    json_object_set_new(root, "request", methodPara);

    return root;
}
```
And the reason of the crash is `json_decref(requestJson)` not only decrease the reference of requestJson but also decrease the reference of methodParaJson, So when I attemp to execute `json_decref(methodParaJson)` after excute ` json_decref(requestJson);`, crash happened frequently.

And the reason why `json_decref(requestJson)` also excute `json_decref(methodParaJson)` is the methodParaJson is wrapped by requestJson.

But I think who is responsible for increase reference, and he also responsible for decrease reference.
So maybe the implementation of function `json_object_set_new` should increase reference?

**Comment by akheron** [comment]
You should use `json_object_set` if you want to use the reference to added value later. `json_object_set_new` "steals" the reference to the added value.

So the correct fix for you is to use `json_object_set(methodPara, methodName.c_str(), parameterJson)` instead of `json_object_set_new(...)`.

**Comment by StarIsCoder** [comment]
It worked. Thanks a lot @akheron
