### ISSUE TITLE
Jansson Generating Documentation

### ISSUE THREAD

**Issue by AmeyaVS** [akheron/jansson#453]
Hello,

Currently I am trying to build the Jansson documentation.
But even after installing the following library using `pip`: [http://www.sphinx-doc.org/en/master/](http://www.sphinx-doc.org/en/master/)

The CMake build is unable to locate the binary, and its version after fiddling with `FindSphinx.cmake`.

How should I setup the environment for generating the documentation?

Currently the `README.md` points to [http://sphinx.pocoo.org/](http://sphinx.pocoo.org/).
Which doesn't looks correct.

Does anyone has any idea on setting the documentation build? Till then I have to disable documentation generation.

-Ameya Vikram Singh

**Comment by ploxiln** [comment]
You probably mean it can't find the binary `sphinx-build` - you need wherever pip puts it to be added to your `PATH`. For example, it might be at `/usr/local/bin/sphinx-build` or it might be in `$HOME/.local/bin/sphinx-build`. In the former case, if you do `export PATH=/usr/local/bin:$PATH` then cmake should be able to find `sphinx-build`.

If you paste here your `pip install` command and its output, the output of `pip --version`, and the `cmake` error output, I may be able to help more.

**Comment by AmeyaVS** [comment]
Hello @ploxiln ,

The `sphinx-build` is available on the `PATH` environment variable.
Currently it is located at `~/.local/bin/sphinx-build`.

And here is the output for the command `sphinx-build --version`:
```sh
$ sphinx-build --version
sphinx-build 1.8.3
$ 
```

**Comment by ploxiln** [comment]
so what's the cmake error

**Comment by ploxiln** [comment]
hmm yeah it does look like the cmake version parsing of sphinx is out-of-date:

https://github.com/akheron/jansson/blob/v2.12/cmake/FindSphinx.cmake#L244-L264

it does `sphinx-build -h` and expects "Sphinx vX.Y.Z" but the help output no longer includes that. It should instead do `sphinx-build --version` and the output is "spinx-build X.Y.Z"

**Comment by AmeyaVS** [comment]
Thanks @ploxiln for the hints.
I was close to fixing it but probably being too late into the night I could not see the regex expression.
I have created a pull-request with the fixes.

-Ameya Vikram Singh

**Comment by AllenX2018** [comment]
> Thanks @ploxiln for the hints.
> I was close to fixing it but probably being too late into the night I could not see the regex expression.
> I have created a pull-request with the fixes.
> 
> -Ameya Vikram Singh

I am not familar with git command to pick commit from your branch, so I have to create a new PR(#502 ) to fix regex expression.

**Comment by coreyfarrell** [comment]
Closing per #502 (unsure why github didn't close automatically).
