### ISSUE TITLE
json_deep_copy does not protect against infinite loop

### ISSUE THREAD

**Issue by coreyfarrell** [akheron/jansson#457]
It appears that using `json_deep_copy` on an object with a circular reference will cause an infinite loop.  Comment from `test_dump.c` circular reference test:

> Construct a JSON object/array with a circular reference:
>
> object: {"a": {"b": {"c": <circular reference to $.a>}}}
> array: [[[<circular reference to the $[0] array>]]]
>
> Encode it, remove the circular reference and encode again.

We need to implement a check for `json_deep_copy`, add testing.

**Comment by AllenX2018** [comment]
I create a PR for this issue and add loop check implementation in deep copy with testing. Pls take a look when you're available
