### ISSUE TITLE
Documentation URL on website returns 404 error

### ISSUE THREAD

**Issue by oxr463** [akheron/jansson#463]
Reproduction Steps:

1) Visit <http://www.digip.org/jansson>.
2) Navigate to "Releases".
3) Click "Documentation", (URL: https://jansson.readthedocs.io/en/2.12).

Results:

The page shows the [readthedocs maze](https://readthedocs.org/404).

--

However, "Comprehensive documentation" in the README,
returns <https://jansson.readthedocs.io/en/latest>, which displays just fine.

Also, navigating to <https://jansson.readthedocs.io>, returns <https://jansson.readthedocs.io/en/2.11>.

**Comment by akheron** [comment]
Fixed, thanks for letting us know!
