### ISSUE TITLE
os x 10.14 autoconf error: This is libtool 2.2.6b, but this LT_INIT comes from libtool 2.4.6.

### ISSUE THREAD

**Issue by davehorton** [akheron/jansson#466]
Any ideas on this one?

I've tried re-running `autoreconf -fi`, which is what seems to be the suggested action, but get the same error.

**Comment by coreyfarrell** [comment]
How did you download jansson?  IE do you have a git clone or a tarball download, and if you have a tarball where did you download from?

**Comment by davehorton** [comment]
git clone from gh

**Comment by coreyfarrell** [comment]
I suspect this is an issue with your local build toolchain, possibly some kind of mismatch among your autotools (aclocal, autoconf, libtool).  I'm not knowledgeable enough about OSX to be able to suggest a fix for this.

If you have cmake you might have better luck using that to build jansson until someone can give a better idea what's going on with your autotools.

**Comment by davehorton** [comment]
I tend to think you're right (about it having to do with my local toolchain).  Closing this.
