### ISSUE TITLE
[feature request] Add json_free function to the API

### ISSUE THREAD

**Issue by davebelliveau** [akheron/jansson#467]
The jsonp_free function, declared in jansson_private.h, frees a buffer using the current memory free function. This function is not part of the "public" API, but I think there's a use case for adding a json_free function to the public API. The use case is:

The documented method for cleaning up output from json_dumps is a call to free(). Code written this way will break if you subsequently attempt to implement a custom allocator. For example:

/* Dump some json and clean it up. */
char* buf = json_dumps(json, 0);
free(buf);

Some weeks/months/years later:

/* Add a customer allocator. */
json_set_alloc_funcs(myMalloc, myFree);

/* Existing code breaks. */
char* buf = json_dumps(json, 0);
free(buf); // this now needs to be changed to myFree(buf)

If a json_free function were added, and json_dumps code used it instead of free(), then custom allocators can be added later without breaking existing code:

/* Dump some json and clean it up. */
char* buf = json_dumps(json, 0);
json_free(buf);

Some weeks/months/years later:

/* Add a customer allocator. */
json_set_alloc_funcs(myMalloc, myFree);

/* Dump some json and clean it up ... still works. */
char* buf = json_dumps(json, 0);
json_free(buf);

If you think this makes sense let me know and I'll create a PR.

**Comment by akheron** [comment]
This has been requested before, and the reasoning for not making `jsonp_free` public was that the user of the library knows the allocator they are using.

Your use case is valid, but I would argue that when a program-wide allocator is changed to something else, the user will have to go through all malloc/free calls anyway, and will spot the problem with freeing `json_dumps` results.

**Comment by davebelliveau** [comment]
I see your point, but it assumes I'm changing the program-wide allocator. In my case, which I admit is edge, I'm only changing the allocator for select libraries. I'm "borrowing" the idea from libxml2. It has its own xmlFree function which is recommended for buffer cleanup throughout the API. If I change the libxml2 allocator, I don't have to think about changing any of the libxml2 code as long as I've used xmlFree. Less change is good.

Anyway, it's easy enough to handle without changing Jansson. Thanks for your consideration.
