### ISSUE TITLE
[bug] api missmatch for json_dumps

### ISSUE THREAD

**Issue by Mephistophiles** [akheron/jansson#471]
In apiref says:
```
The return value must be freed by the caller using free().
```
but it allocated by ``jsonp_strdup``, therefore it should be cleaned through jsonp_free

it was revealed when changing the allocator, which adds poison to the beginning of the data. (adds 4 bytes with pattern)

maybe worth fixing the documentation.

**Comment by AllenX2018** [comment]
I notice this problem too.And I also find that jsonp_free is not export as API in jansson.h.So in my opinion, it should be mentioned in the doc that "the return value should be freed by the caller using free(),or your custom free() in self-defined allocator case"

**Comment by coreyfarrell** [comment]
My preference is to update the documentation with a note that if you have a custom malloc / free that you must use your custom free function.  Not sure the best wording for this.  I'm not interested in exposing the `jsonp_*` functions.
