### ISSUE TITLE
json_loadf not allow to mix fhandle functions

### ISSUE THREAD

**Issue by CicTec** [akheron/jansson#472]
Hello,

according to the documentation, json_loadf allows loading JSON from a file handle (for example a TXT), furthermore using internally FGETC to read the characters should position the file position indicator to be able to call other functions json_loadf (obviously if the json_disable_eof_check flag is used) or other handle functions (fgetc, fgets, etc ...), however it does not seem to work (at least in Linux).

Having the following TXT:
=== remark line 1 ===
{ "data_int": 10, "data_float": 30.23, "data_string": "name" }
=== remark line 2 ===

And the following code:
FILE *f;
f = fopen ("json_data.txt", "r");
if(f) {
  char s_remark_1 [64];
  char s_remark_2 [64];
  json_t json_obj;

  fgets(s_remark_1, 64, f);
  json_obj = json_loadf(f, JSON_DISABLE_EOF_CHECK, NULL);
  fgets(s_remark_2, 64, f);
  fclose(f);
}

The first remark line is loaded into s_remark_1, then the JSON is read correctly and loaded into json_obj, while the last call to fgets to retrieve === remark line 2 === in s_remark_2 fails.

I think there is a bug in the function (otherwise it would be of little use to use FILE in this way).

I haven't tried it if it works in Windows, but in Linux (Ubuntu 16.04 64bit) it causes the reported issue.

**Comment by coreyfarrell** [comment]
The documentation for `json_loadf` states `the file position will be at the first character after the last ] or } in the JSON input`.  In your example text this is the linefeed.  So the next call to `fgets` returns an empty string, an additional call to `fgets` will return your remark 2.

**Comment by CicTec** [comment]
Thanks for reply, but I think the function should position itself over a linefeed so that a subsequent call as fgets can read the next line and keep a homogeneous example as for fputs.

**Comment by coreyfarrell** [comment]
If we used `fgetc` until we get a non-whitespace character we would have to fseek to go back to the previous character (so the next fgetc would get the first non-whitespace character).  This would fail on non-seekable streams.  The point of being able to use this function multiple times on the same file is to read files such as:
```
{"id": "object1"}
{"id": "object2"}
```

Where the first call would get `{"id": "object1"}` and the second would get `{"id": "object2"}`.  The second call eats the whitespace before object2.  This also supports situations where multiple objects are on the same file, so `{"id": "object1"}{"id": "object2"}`.  I understand that this function does not work exactly as you'd like but I think it works correctly.

**Comment by ploxiln** [comment]
I have seen some (custom) file formats like `<json-object><binary-trailer>` and in some formats it is possible for the "binary-trailer" to sometimes start with a byte value that just happens match an ascii `\r` or `\n` (and the caller wants to get the whole binary-trailer without ambiguity of whether some initial bytes were skipped). I think jansson's interface intends to support arbitrary cases like this. The caller of jansson can advance over ascii whitespace pretty easily if appropriate.

**Comment by CicTec** [comment]
@coreyfarrell, @ploxiln, thanks for the answers.

I think that the code has to be corrected (or improved) because not that homogeneity between the use of dumpf and its equivalent of loadf.
The use of handles should have the advantage of being able to mix in a text file corresponding to JSON and non-corresponding text (since for JSON text only other specific functions exist in the library).
So back to the previous example, we have a code like this:
FILE *f;
f = fopen("json_data.txt", "w");
if(f) {
  json_t json_obj;

  // json_obj filled with code ....

  fputs("=== remark line 1 ===", f);
  json_obj = json_dumpf(f, json_obj, JSON_ENCODE_ANY,);
  fputs("=== remark line 2 ===", f);
  fclose(f);

If we open the file we see 3 lines of code, this is because dumpf adds a new line escape code after the JSON code.

If we want to recover homogeneously the text we should use the code previously mentioned:
FILE *f;
f = fopen("json_data.txt", "r");
if(f) {
  char s_remark_1[64];
  char s_remark_2[64];
  json_t json_obj;

  fgets(s_remark_1, 64, f);
  json_obj = json_loadf(f, JSON_DISABLE_EOF_CHECK, NULL);
  fgets(s_remark_2, 64, f);
  fclose(f);

But obviously as reported, this does not work (the third line is not recovered) this because there this because there is no homogeneous correspondence to how dumpf saves and how loadf retrieves, so I think that loadf should be modified or maybe add new flags to encoding/decoding to avoid this problem.

**Comment by ploxiln** [comment]
If you do not use `JSON_INDENT()` then `json_dumpf()` does not add a newline char at the end. And `fputs()` does not add a newline char either! (Only `puts()` does.)

**Comment by CicTec** [comment]
@ploxiln, I tried the example before posting it by opening the file, this is the result I get in my machine (ubuntu 16.04 LTS 64bits).
I didn't use JSON_INDENT () (see the example) but dumpf added the newline.

**Comment by CicTec** [comment]
@ploxiln, even if it worked as you say and then dumpf added the newline, loadf would skip it otherwise you continue to have no homogeneity between functions and the previous example could not be used.

**Comment by coreyfarrell** [comment]
@CicTec I just tested your example code, after fixing the compile errors it did work:
```c
#include "jansson.h"
#include "stdio.h"

int main(int argc, char argv[])
{
	FILE *f = fopen("json_data.txt", "w");
	if (!f) {
		return 1;
	}

	json_t *obj = json_pack("{ss}", "name", "value");

	fputs("=== remark line 1 ===\n", f);
	json_dumpf(obj, f, 0);
	fputs("=== remark line 2 ===\n", f);
	fclose(f);
	return 0;
}
```
This produced json_data.txt:
```
=== remark line 1 ===
{"name": "value"}=== remark line 2 ===
```

Even with `JSON_INDENT(4)` there is no trailing `\n` on the output of json_dumpf, the following is the output:
```
=== remark line 1 ===
{
    "name": "value"
}=== remark line 2 ===
```

**Comment by CicTec** [comment]
@coreyfarrell, ok, but in any case it would be interesting that loadf and dumpf have a system (perhaps with flags) that allows to add an escape like \n, \t, etc ... beyond the } for example and position with loadf beyond the escape, so that the example I posted at the beginning is possible, otherwise it can be difficult to mix library functions with fputs / fgets.
