### ISSUE TITLE
json_unpack returns incorrect int value when also unpacking a bool

### ISSUE THREAD

**Issue by spdev31** [akheron/jansson#473]
Hello all,

We found unpacking an int and a bool with json_unpack returns an incorrect int value.

Input: {myInt:2,myBool:true}
Format String: {s:i,s:b}
Output: myInt = 0, myBool = true
Expected: myInt = 2, myBool = true

A workaround is to call json_unpack for the int only then call json_unpack for the bool only.  Strangely enough, changing the format string to decode the bool first then the int gives the correct value for both variables (i.e. {s:b,s:i}).

We've attached source code below showing the failing case:
[main.zip](https://github.com/akheron/jansson/files/3082789/main.zip)

Please let us know if there is any advice/fix for this issue - thanks for your help.

Best Regards,
Shaun

**Comment by spdev31** [comment]
Closing.   Our code incorrectly uses the 'bool' type instead of an 'int' type for the 'b' format specifier passed to json_unpack.  Switching to int resolves the issue.  Many thanks to Graeme Smecher for identifying the root cause.

**Comment by gsmecher** [comment]
Happy to help!
