### ISSUE TITLE
Change JANSSON_ATTR so that we support pre-C99 compilers

### ISSUE THREAD

**Issue by JamesAllwrightAA** [akheron/jansson#481]
Problem report regarding "Build: Add JANSSON_ATTRS macro. #404"

The JANSSON_ATTRS() macro relies on C preprocessor (CPP) handling of
variadic macros which is a C99 feature. I am seeing compilation failures
where the wrong number of parameters is reported as an error for the
json_sprintf and json_vsprintf() declarations because I am using a
compiler which does not support the C99 features.  Note that there are
still variadic C functions in the code, but these are OK because they
are supported in an earlier C standard (C89) whereas CPP variadic macros
are not supported until C99.

As a fix for this, I propose the following code changes in jansson.h :
```
#if defined(__GNUC__) || defined(__clang__)
#define JANSSON_ATTRS(x) __attribute(x)
#else
#define JANSSON_ATTRS(x)
#endif
```
and then elsewhere in the code where we use warn_unused_result, we use e.g.
```
json_t *json_object_get(const json_t *object, const char *key) JANSSON_ATTRS((warn_unused_result));
```
and around line 300
```
json_t *json_sprintf(const char *fmt, ...) JANSSON_ATTRS((warn_unused_result, format(printf, 1, 2)));
json_t *json_vsprintf(const char *fmt, va_list ap) JANSSON_ATTRS((warn_unused_result, format(printf, 1, 0)));
```

**Comment by akheron** [comment]
Fixed in #501
