### ISSUE TITLE
[bug] Random object order not allowed?

### ISSUE THREAD

**Issue by xback** [akheron/jansson#493]
Using json_unpack_ex() requires the objects to be in a specific order, even when a name is passed.

Example:

json_unpack_ex(root, &Err, 0, "{s?o, s?o, s?o}", \
	"general", &general, \
	"names", &names, \
	"cars", &cars);

requires that the objects "general", "names" and "cars" have been defined in the same order in the root object.

In the example below,  "names" and "general" will be NULL as they are swapped

json_unpack_ex(root, &Err, 0, "{s?o, s?o, s?o}", \
	"names", &names, \
	"general", &general, \
	"cars", &cars);

This seems illogical, as there is nothing wrong with this according to JSON spec?

It should be possible to have a flag or so which tells the functions to search all found objects at this level until the corresponding name has been found at any location:

like:
#define JSON_ALLOW_UNDEF_ORDER         0x3

Edit:
Looks like this issue is only present when parsing objects using this unpack function
using it for other types (strings, ints) seems to allow out-of-order

**Comment by akheron** [comment]
Can't reproduce. Here's a test program I used. Feel free to reopen and provide a minimal reproducing program that demonstrates the issue.

```
#include <jansson.h>

int main() {
    json_error_t Err;
    json_t *root = json_loads("{\"general\": [42], \"names\": {}, \"cars\": true}", 0, &Err);

    json_t *names, *general, *cars;

    int res = json_unpack_ex(root, &Err, 0, "{s?o, s?o, s?o}",
                   "names", &names,
                   "general", &general,
                   "cars", &cars);

    printf("%d, %p, %p, %p\n", res, names, general, cars);
    return 0;
}
```

**Comment by xback** [comment]
Hi,

Here is a reproducer:

```
#include <jansson.h>

int main() {
    json_error_t Err;
    json_t *root = json_loads("{\"obj1\":{\"test1\":\"test 1\"},\"obj2\":{\"test2\":\"test 2\"},\"obj3\":{\"test3\":\"test 3\"},\"obj4\":{\"test4\":\"test 4\"}}", 0, &Err);

    json_t *test1, *test2, *test3, *test4;

    int res = json_unpack_ex(root, &Err, 0, "{s?o, s?o, s?o, s?o}",
                   "test1", &test1,
                   "test2", &test2,
                   "test3", &test3,
                   "test4", &test4);

    printf("%d, %p, %p, %p, %p\n", res, test1, test2, test3, test4);
    return 0;
}
```

This is the JSON input:
```

{
  "obj1": {
    "test1": "test 1 ok"
  },
  "obj2": {
    "test2": "test 2 ok"
  },
  "obj3": {
    "test3": "test 3 ok"
  },
  "obj4": {
    "test4": "test 4 ok"
  }
}

```
Output of the app here is:

`0, 0x7fff7a46e8d8, 0x7fff7a46e910, 0x7fa30eabb710, (nil)`

So the call succeeds, put the pointer of the last object in the input is NULL.

Reversing the order in `json_unpack_ex()`:

```
#include <jansson.h>

int main() {
    json_error_t Err;
    json_t *root = json_loads("{\"obj1\":{\"test1\":\"test 1\"},\"obj2\":{\"test2\":\"test 2\"},\"obj3\":{\"test3\":\"test 3\"},\"obj4\":{\"test4\":\"test 4\"}}", 0, &Err);

    json_t *test1, *test2, *test3, *test4;

    int res = json_unpack_ex(root, &Err, 0, "{s?o, s?o, s?o, s?o}",
                   "test4", &test4,
                   "test3", &test3,
                   "test2", &test2,
                   "test1", &test1);

    printf("%d, %p, %p, %p, %p\n", res, test4, test3, test2, test1);
    return 0;
}
```

Yields the following output

`0, **(nil)**, 0x7f151507d710, 0x7ffe3dc09c50, 0x7ffe3dc09c18`

**Comment by coreyfarrell** [comment]
json_unpack_ex will not find `test1` inside `obj1` using this statement. is not finding any of the objects and the pointers being printed are undefined.  The correct unpack call for this structure would be:
```c
    int res = json_unpack_ex(root, &Err, 0, "{s: {s?o}, s: {s?o}, s:{s?o}, s:{s?o}}",
                   "obj1", "test1", &test1,
                   "obj2", "test2", &test2,
                   "obj3", "test3", &test3,
                   "obj4", "test4", &test4);
```
Also note you need to initialize the pointer variables to NULL before calling json_unpack_ex.  json_unpack_ex does not touch variables for keys that are not found.  That is why you were seeing "random" pointers, it was showing whatever appeared on the stack.

**Comment by xback** [comment]
Yeah, noticed the typo and thus deleted the faulty repro.

I guess I'll have to share the full json config at some point.  which is pretty huge.
or do some more checking until it works and check the delta.

Will come back on this when I have more facts & figures.

Thanks again for taking the time here to check it.
