### ISSUE TITLE
How to properly change some of jansson function names ?

### ISSUE THREAD

**Issue by jetacpp** [akheron/jansson#495]
Hello,
Due to conflict with libparson, I attempted to change some of jansson function names. After compiling libjansson.a, new symbols were found and everything was alright.
However, libjansson.so had new function names scoped local to the library ( nm output shows -t instead of T).
I looked around and updated jansson.def to have the new function names updated but the effect was still the same. Where should I go about to make the build system completely switch to new function names for both .a and .so library outputs ?
Thank you !

**Comment by akheron** [comment]
Libtool publishes some functions based on a regexp, see:

https://github.com/akheron/jansson/blob/76300601d9cb3f8756dd94f0f8a354ff844ae686/src/Makefile.am#L27

There's some documentation e.g. here: https://autotools.io/libtool/symbols.html
