### ISSUE TITLE
make check error

### ISSUE THREAD

**Issue by amrithathorath** [akheron/jansson#497]
I've successfully run the following commands:

- ./configure
- make
- sudo make install

But when I run "make check", I see the following error:

```
FAIL: run-suites
==============================================================
Testsuite summary for jansson 2.12
==============================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
==============================================================
See test/test-suite.log
Please report to petri@digip.org
==============================================================

```

The "test/test-suite.log" file shows this error: 

```
.. contents:: :depth: 2

FAIL: run-suites
================

../test-driver: line 107: ./run-suites: Permission denied
FAIL run-suites (exit status: 126)
```
I've run "make check" with and without sudo but still see the same error.
I've set LD_LIBRARY_PATH to /usr/local/lib" (default install location of library).

**Comment by madf** [comment]
Looks like `run-suites` does not have executable bit.

**Comment by amrithathorath** [comment]
Thanks a lot for that... That fixed my issue...

**Comment by coreyfarrell** [comment]
`make check` runs against build results in the source directory.  It can/probably should be run before `make install`.

Additionally `run-suites` does have the executable bit set in git, I just verified this with a fresh `git clone`.  Not sure why your git client ignored this.

**Comment by amrithathorath** [comment]
I downloaded the zip file instead of git clone...

**Comment by coreyfarrell** [comment]
Can you please share the URL you used to download a ZIP file?
