### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by jxdeng3264** [akheron/jansson#516]
How to create the **cjose_jwk_t**  use  **cjose_jwk_import** function.
cjose_jwk_import  use in param key.  But How To Construct the Key String.
cjose_jwk_t *cjose_jwk_import(const char ***jwk_str**, size_t len, cjose_err *err)

**Comment by coreyfarrell** [comment]
It appears you've opened this against the wrong repository, these functions are not part of jansson.
