### ISSUE TITLE
Add format specifier for 'number'

### ISSUE THREAD

**Issue by Zer0-One** [akheron/jansson#519]
It seems like in every case that a document might include a floating point value written as an integer (i.e, with no decimal point), the user has to parse the value as a generic JSON value, then call `json_is_number()`, then call `json_number_value()`. For a lengthy document, this quickly becomes very inconvenient and ugly-looking.

Given that this is such a consistent pattern, would it make sense to add a `json_unpack()` format specifier for `number`, to be used instead of explicitly specifying `real` or `integer`?

**Comment by akheron** [comment]
The `F` format specifier does exactly this.

**Comment by Zer0-One** [comment]
lol how on earth did I not see that :laughing:
