### ISSUE TITLE
 State Error	C1083	Cannot open include file: 'stdarg.h': No such file or directory	

### ISSUE THREAD

**Issue by Elaineev** [akheron/jansson#524]
When i deguging the simple_parse.exe, it keep shows this error.
May i know what is the issue of this?

**Comment by akheron** [comment]
There's something wrong with your environment. stdarg.h is a standard header already in C89, so all modern compilers should support it.

I'm not familiar with MSVC, but maybe you need to somehow set the project's language to C instead of C++?
