### ISSUE TITLE
Docs search is broken

### ISSUE THREAD

**Issue by trebinor** [akheron/jansson#525]
1. Click the [docs link](http://jansson.readthedocs.io/en/latest/) in README.rst.
2. Search for anything.  Ex. JSON_STRICT
3. All results are relative to https://shellgui-docs.readthedocs.io instead of https://jansson.readthedocs.io, and therefore broken.  In fact, https://jansson.readthedocs.io is redirecting to https://shellgui-docs.readthedocs.io/en/2.12/.

**Comment by akheron** [comment]
Seard works for me now, though I noticed that http://jansson.readthedocs.io (without https) still redirects to this shellgui-docs project.

**Comment by akheron** [comment]
Umm, actually even with https it seems to redirect to the other project.

**Comment by akheron** [comment]
Reported at https://github.com/readthedocs/readthedocs.org/issues/6672

**Comment by trebinor** [comment]
Appears to be working now after the activity over at  [readthedocs](https://github.com/readthedocs/readthedocs.org).  Thanks for filing that.
