### ISSUE TITLE
Does replacing a key decrements the reference count ? 

### ISSUE THREAD

**Issue by Sunslash** [akheron/jansson#529]
Hello,
I am currently writing an application using jansson, and I would like to avoid any memory issues.

Let's say I have added a key to a json object
`json_object_set_new(my_json, "key", my_value);`

And then later decide to replace the value
`json_object_set(my_json, "key", my_new_value);`

What happens to the old json object ? Is it decremented and destroyed ? Or should I manage this myself ?

**Comment by Mephistophiles** [comment]
Yep, it will be decremented and destroyed. Stacktrace:

* hashtable_set https://github.com/akheron/jansson/blob/4c9018cc4c372f33013806ce7914fda965e3f9aa/src/hashtable.c#L209-L212
* json_object_set_new_nocheck https://github.com/akheron/jansson/blob/4c9018cc4c372f33013806ce7914fda965e3f9aa/src/value.c#L117
* json_object_set_new https://github.com/akheron/jansson/blob/4c9018cc4c372f33013806ce7914fda965e3f9aa/src/value.c#L131
* json_object_set https://github.com/akheron/jansson/blob/4c9018cc4c372f33013806ce7914fda965e3f9aa/src/jansson.h#L225-L226

**Comment by Sunslash** [comment]
Perfect, thanks
