### ISSUE TITLE
Documentation generation fails with Sphinx 3

### ISSUE THREAD

**Issue by stratakis** [akheron/jansson#530]
Hello,

On Fedora we are testing packages that depend on the latest version on Sphinx and jansson was one of the packages that failed to generate their documentation.

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1823532

Error message:
Making html in doc
make[1]: Entering directory '/builddir/build/BUILD/jansson-2.12/doc'
sphinx-build -b html -d _build/doctrees  . _build/html
Running Sphinx v3.0.2
Exception occurred:
  File "/builddir/build/BUILD/jansson-2.12/doc/ext/refcounting.py", line 60, in setup
    app.add_directive('refcounting', refcounting_directive, 0, (1, 0, 0))
TypeError: add_directive() takes from 3 to 4 positional arguments but 5 were given

Changelog of Sphinx 3: https://www.sphinx-doc.org/en/master/changes.html#release-3-0-0-released-apr-06-2020

**Comment by akheron** [comment]
Would you be interested in creating a PR for this?

**Comment by stratakis** [comment]
Unfortunately I do not have much time to work on that. I might check it out again from next week.

**Comment by Zer0-One** [comment]
This is blocking removal of older Sphinx versions in Gentoo. I tried to have a go at patching it myself, but with no working knowledge of Sphinx or docutils I wasn't able to figure it out in the bit of time I had set aside for it.
