### ISSUE TITLE
jansson and json-c  libraries have symbol conflicts

### ISSUE THREAD

**Issue by vysakh-av** [akheron/jansson#536]
**Describe the bug**
In the application, we are using a shared library which is using json-c for its internal purpose. Later our application required to use a third party library, but its internally used jansson inside it for its functionality. Unfortunately when we run the application , it leads to memory corruption and process crashed.

Both of these libraries have multiple APIs with same name but different signature.
Due to this, there is a memory corruption that resulted in crash.

The following APIs are available in both json-c and jansson libraries with the same name:
**json_object_get
json_object_iter_next**

**Steps To Reproduce**
This issue can easily reproduce with the following way:

- Application linked to libjson_c_lib.so and libjansson_c_lib.so. Both of these are wrapper libraries are using json-c and jannson internally.

- libjson_c_so wrapper library linked to libjson-c.so

- libjansson_c.so wrapper library linked to libjansson.so.

**Tried statically linked one of the library but its not helped here. If we statically link jansson to wrapper library,  crash resolved but json-c calls failed especially json_tokener_parse().** 

Please see below the crash dump:

(gdb) bt
#0  0x00007ffffea35428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffffea3702a in __GI_abort () at abort.c:89
#2  0x00007ffffea777ea in __libc_message (do_abort=do_abort@entry=2,
    fmt=fmt@entry=0x7ffffeb90ed8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffffea8037a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>,
    str=0x7ffffeb8dcaf "free(): invalid pointer", action=3) at malloc.c:5006
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3867
#5  0x00007ffffea8453c in __GI___libc_free (mem=<optimized out>) at malloc.c:2968
#6  0x00007ffffe7f8549 in json_delete_object (object=0x603010) at value.c:78
#7  json_delete (json=0x603010) at value.c:935
#8  0x00007ffffedd091e in json_decref (json=0x603010) at /usr/local/include/jansson.h:112
#9  0x00007ffffedd0b14 in jansson_c_lib_init (buffer=0x7ffffffed250 "{\n\"name\":\"vysakh\",\n\"age\":32\n}\n")
    at /home/vysakhav/exper-library-conflict/jansson_c_lib.c:44
#10 0x0000000000400c0d in main () at /home/vysakhav/exper-library-conflict/app.c:58
(gdb)

**Comment by akheron** [comment]
This is unfortunate, but I'm afraid nothing can be done in the jansson side to fix this problem.

There are a few ways to fix it in your application:

- Change your own shared library to use jansson instead of json-c
- Ship the json-c source with your shared library, and modify it by renaming the conflicting functions
- Ship the jansson and the third party library source with your application, and rename the conflicting functions in both

**Comment by rwmjones** [comment]
This should be fixed by symbol versioning I think? (https://github.com/akheron/jansson/pull/540)

**Comment by akheron** [comment]
Correct!
