### ISSUE TITLE
"Thread safety" is documented in "Portability" section

### ISSUE THREAD

**Issue by i-ky** [akheron/jansson#545]
Most of the contents of "Thread safety" section seems to be relevant regardless of platform being used. Thread safety is also an important topic on its own and for some users it may be even more important than portability. I would propose to move "Thread safety" to its own chapter and link to certain parts of it from "Portability".

**Comment by akheron** [comment]
You’re right. The whole “Portability” section’s name could be changed to “Thread safety”, as it’s only about thread safety.

**Comment by i-ky** [comment]
Yes, indeed.

**Comment by akheron** [comment]
Fixed
