### ISSUE TITLE
Relaxed JSON

### ISSUE THREAD

**Issue by gonzus** [akheron/jansson#547]
I am using jansson in one of my personal projects, and loving it.

Question: any plans to support a "relaxed" version of JSON, for some definition of relaxed? From the top of my head:
* Support some form of comments: `//`, maybe `#`, even `/* ... */`:
```json
// this is the JSON config for my frobnicator
{
    "schema": "frobnicate",
    // ...
}
```
* Support trailing commas at the end of arrays / objects (which makes it easier to reformat / move things around):
```json
[
    "first string",
    {
        "foo": 42,
        "bar": true,
    },
    "another one",
    "final string!",
],
```
* Support object keys without quotes: `{ foo: 1, bar: "hello" }`.
* Support quoting with `'` in addition to `"`: `{ bilbo: "I'd like that", frodo: 'He is "away"' }`.

Thanks!

**Comment by gsmecher** [comment]
YAML (http://yaml.org) gives you all of these features, and JSON5 (http://json5.org) or HJSON (https://www.npmjs.com/package/hjson) give you most of them. There may be good C parsers for these formats, but Jansson is a JSON parser and these extensions are objectively not JSON.

(#13, #215, #232, #235, ...)

**Comment by gonzus** [comment]
Thanks for the pointers. JSON5 looks like an almost perfect fit for what I am looking for. But I also see how this has been raised in the past and the author has decided not to support it. His project, his rules.

Cheers!
