### ISSUE TITLE
find the json_t object size in bytes

### ISSUE THREAD

**Issue by zuoshuluHTC** [akheron/jansson#549]
I am working on a program that runs on a hardware with a very small size RAM, it seemed like I ran out of memory. Is there a way to find out how big is a json_t object, my object includes some directories of different values like integer, string, and boolean. I tried the sizeof function, but it always return 4.

**Comment by akheron** [comment]
I'm afraid there's no such function. A `json_t` is a complex value, and its size may differ greatly if the value is e.g. an object.
