### ISSUE TITLE
Return key length in `json_object_foreach`

### ISSUE THREAD

**Issue by gonzus** [akheron/jansson#581]
On every iteration, this macro returns the object key in a `const char*` variable. This means that, if the length of this key is required, one needs to call `strlen` on the key. Would it be possible to add a way to retrieve the key string and its length (which I assume is known inside the library)?

I am not providing any examples because I am not sure what such an API would look like ideally.

**Comment by akheron** [comment]
The master branch has [`json_object_ketlen_foreach`](https://jansson.readthedocs.io/en/latest/apiref.html#c.json_object_keylen_foreach) for this use case.

**Comment by gonzus** [comment]
Fantastic, will migrate to that as soon as there is a release. Closing the issue.
