### ISSUE TITLE
Pointer to array data

### ISSUE THREAD

**Issue by yigithsyn** [akheron/jansson#594]
Is it possible to get double pointer of JSON_ARRAY data which consists of JSON_REAL numbers?

Thank you.

**Comment by akheron** [comment]
No, but you can build such an array yourself by allocating a C array, iterating over the json array and copying the values over.

**Comment by yigithsyn** [comment]
Thanks for quick response. But still I appreciate if you think about it in future enhancements. Great work. Thank you.
