### ISSUE TITLE
RPC: add json_array_swap_remove for O(1) remove from an array

### ISSUE THREAD

**Issue by Mephistophiles** [akheron/jansson#601]
If it is helpful for jansson, I glad to  create a PR to add the `json_array_swap_remove` function like in rust lang (https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.swap_remove)

This new function makes removing from an array faster when preserving ordering is not required.

**Comment by akheron** [comment]
This doesn't sound very helpful to me. Implementing algorithms is better done with faster/leaner data structures than Jansson's internal representation.
