### ISSUE TITLE
ld.gold: --default-symver: unknown option; ld.bfd: 1 of 5 test suites failed 

### ISSUE THREAD

**Issue by sassy-crick** [akheron/jansson#605]
Dear all,
I am having an issue with the latest version of Jansson (2.14) and `GCC-11.2.0` on Debian Linux (bullseye).
Using the `ld.gold` linker, which is the default in EasyBuild, the compilation crashes with `--default-symver: unknown option`.
Switching to the `ld.bfd` linker it builds, but one test is failing (see attached file).
So I am a bit stuck between a rock and a hard place. I should add that the previous version, which does not have the `--default-symver` flag, compiles without a problem. My problem might be related to issue [528](https://github.com/akheron/jansson/issues/528). However, I should point out as I am using EasyBuild, the OS should not play too much of a role here. 
Any suggestions how to solve this problem? I am happy to provide more information if required. 
Thanks for your help!

Jörg

[stderr.txt](https://github.com/akheron/jansson/files/8171555/stderr.txt)

**Comment by dukess** [comment]
Same problem.
As a workaround you can use cmake instead ./configure:
```
mkdir -p build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DJANSSON_BUILD_SHARED_LIBS=ON ..
make all
make install
cd ..
```

**Comment by sassy-crick** [comment]
Switching to `CMake` did the trick for me, many thanks!
