### ISSUE TITLE
json_get_alloc_funcs() is not used where it should be.

### ISSUE THREAD

**Issue by dokutoku** [akheron/jansson#625]
[This line](https://github.com/akheron/jansson/blob/128e9c5f376ac425f13d3b1cf9a38d53e544ad23/test/bin/json_process.c#L224) and [this line](https://github.com/akheron/jansson/blob/128e9c5f376ac425f13d3b1cf9a38d53e544ad23/test/ossfuzz/json_load_dump_fuzzer.cc#L112) should not use the free() function, but should use jsonp_free() or the free function obtained with json_get_alloc_funcs().

**Comment by akheron** [comment]
Jansson uses `malloc` by default, so using `free` is correct in programs that don't call `json_set_alloc_funcs`.
