### ISSUE TITLE
Parsing of \u0000

### ISSUE THREAD

**Issue by j-moeller** [akheron/jansson#690]
Hello,

we found an issue in jansson when dealing with "\u0000" in a string. You can find a minimum working sample here: [1](https://github.com/j-moeller/crossy-mws/tree/master/03-04-06-control-characters/jansson).

**Comment by akheron** [comment]
You must use the `JSON_ALLOW_NUL` decoding flag as described here: https://jansson.readthedocs.io/en/latest/apiref.html#decoding
