### ISSUE TITLE
Documentation doesn't specify that json_object_get() doesn't increase reference count.

### ISSUE THREAD

**Issue by Napoleon-42** [akheron/jansson#703]
Hi,

The documentation say that: 

> Normally, all functions accepting a JSON value as an argument will manage the reference, i.e. increase and decrease the reference count as needed.

But `json_object_get(object, key)` doesn't increase the 'object' refcount. This could be miss-leading.
Is an addition to the `json_object_get()` function description, specifying that it doesn't increase the refcount, would be a desired change?

Thanks:)

**Comment by akheron** [comment]
The previous paragraph says:
> Other functions returning (existing) JSON values do not normally increase the reference count. These functions are said to return a **borrowed reference**.

The documentation of json_object_get says:
> Return value: Borrowed reference.

I think this is quite clear.

**Comment by Napoleon-42** [comment]
Ah, true, my bad.

Thanks :+1:
