### ISSUE TITLE
large numbers create an error "too big integer near ..."

### ISSUE THREAD

**Issue by scumola** [akheron/jansson#8]
Hey there.  If a mega-large integer is encountered in the json data, I get a 'too big integer near ...' error.  Can we check to see if the integer is > maxint, and then store it as a string or something instead of failing to parse the json data?

I'm trying to parse the twitter stream using the lib and it's choking on this json string part:
... ,"id_str":"6572981622935552", ...
- Steve Webb

**Comment by Dinesh-Ramakrishnan** [comment]
@akheron Did you had a chance to add the Flag to get all numbers as strings?
My system doesnt support long long as well as strtoll. So I prefer to get the value returned as string instead..  Currently I am getting error ""too big integer near" on parsing

**Comment by akheron** [comment]
There's no option to get all numbers as strings, but there is an option to get all numbers as reals (doubles). This might help if your system doesn't support 64-bit integers.

**Comment by Dinesh-Ramakrishnan** [comment]
@akheron : Do you mean using JSON_DECODE_INT_AS_REAL flag in json_loads?  I will try and reply back . Thank you

**Comment by Dinesh-Ramakrishnan** [comment]
@akheron : With the following code also i am getting the same error

json_loads(response, JSON_DECODE_INT_AS_REAL, &error):
The integer is 12 numbers (1443685027007) a timestamp in ms resolution.
